### PR TITLE
Fix & refactor server routing + add tests

### LINKED ISSUE #796: Extension-less url with dot after last slash is not accessible
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus >= 1.2.0
Only in development server .. production has no issue

### Steps to Reproduce

1. Set `cleanUrl` in `siteConfig` as true
2. Create a `2018-05-27-1.13.0.md` file in blog folder
```
---
author: Lucas Duailibe (@duailibe)
authorURL: https://twitter.com/duailibe
title: "Prettier 1.13: Conquering the web!"
---

This releases adds support for several new syntax features, formatting fixes and first-class support for working in the browser.
```
3. Start development server
```
cd website
yarn start
```
4. Open http://localhost:3000/blog/2018/05/27/1.13.0

### Expected Behavior
Page is accessible just like http://localhost:3000/blog/2018/05/27/1.13.0/ and http://localhost:3000/blog/2018/05/27/1.13.0.html

after2

### Actual Behavior
Page is not accessible

before2

### Analysis
This is happening because there is no path that match the extension-less url
The only routing for extension-less url expect that there should be no '.' after last slash
https://github.com/facebook/Docusaurus/blob/c5661b0e1e131803709852adc2283fb4894aabcc/lib/server/server.js#L537-L565

However, the fix isn't as simple as changing above regex to allow any occurences of '.' after last slash because this means that request like `/robots.txt`, `/test.html` will match that and we can possibly hit infinite loop `/robots.txt/index.html` -> `/robots.txt/index.html/index.html` with above logic

### Reproducible Demo

https://github.com/yangshun/prettier/tree/docu

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Changes

- Fix `sitemap.xml` routing to be properly on it's correct place.
Example: when baseUrl is `/jest/`, it should only be accessible at `/jest/sitemap.xml` and not at `/sitemap.xml`
- Fix `blog/atom.xml` and `blog/feed.xml` routing to be properly in it's correct place
- Fix wrong logic/ bug where `blog/test.xml` or any `blog/*.xml` will send `blog/feed.xml`
- Fix wrong logic at blog routing in which if file does not exist, we properly exit (not send wrong file) & use `next` middleware function
- Fix page routing regex, previously all `.html` files will hit this path, we should ignore it if it's `docs` or `blog` pages. 100% more efficient
- Add a lot of tests with jest to catch regression & routing regex are refactored to `lib/core/routing.js` so that our routing is still true in v2
- Refactor extension-less url routing + add test
- Fix #796 by adding dot routing (special case like `http://localhost:3000/blog/2018/05/27/1.13.0` + test

Before
before2

After
working

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Test in development, everything work as per normal
working

### CODE REVIEW

**Comment by endiliey** [comment]
Just realized that we have a lot of bugs & inefficient regex for our server routing. 😂 
Please take your time to review this @yangshun @JoelMarcey

**Comment by JoelMarcey** [comment]
I don't think this PR fixes it since just deals with the server and not `generate.js`, but we have a slight sitemap problem.

https://docusaurus.io/sitemap.xml

It contains - `https://docusaurus.io/2017/12/14/introducing-docusaurus` and `https://docusaurus.io/2018/04/30/How-I-Converted-Profilo-To-Docusaurus`

But that is the wrong URL - it should be `https://docusaurus.io/blog/2017/12/14/introducing-docusaurus` and `https://docusaurus.io/blog/2018/04/30/How-I-Converted-Profilo-To-Docusaurus`

Even shows on Google Search Console.

screenshot 2018-06-24 21 12 51

**Comment by endiliey** [comment]
@JoelMarcey #801 should fix it 😂

File: lib/server/server.js [hunk 1]
```diff
@@ -257,26 +283,30 @@ function execute(port, options) {
...
-  app.get(/blog\/.*xml$/, (req, res) => {
+  app.get(feedRouting(siteConfig.baseUrl), (req, res, next) => {
     res.set('Content-Type', 'application/rss+xml');
-    let parts = req.path.toString().split('blog/');
-    if (parts[1].toLowerCase() == 'atom.xml') {
+    let file = req.path
+      .toString()
+      .split('blog/')[1]
+      .toLowerCase();
+    if (file == 'atom.xml') {
```
Comment (yangshun) [inline lib/server/server.js]: Nit - `===`

File: lib/server/server.js [hunk 2]
```diff
@@ -257,26 +283,30 @@ function execute(port, options) {
...
       res.send(feed('atom'));
-      return;
+    } else if (file == 'feed.xml') {
```
Comment (yangshun) [inline lib/server/server.js]: Nit - `===`
