### PR TITLE
fix(v2): handle multiple asset links in one line properly

### LINKED ISSUE #3631: Linking multiple PDFs in one line causes parsing error
## 🐛 Bug Report

Linking multiple PDFs in one line in a `.md` file causes parsing error.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Create a folder in the `static` folder called `content`
2. In the `content`, folder, run the following commands to download sample pdfs:
```bash
wget https://www.kungfoomanchu.com/guides/andy-klise-3x3x3-speedcubing-guide-v4.pdf
wget https://www.kungfoomanchu.com/guides/andy-klise-3x3x3-speedcubing-guide-v4-lefty.pdf
wget https://www.kungfoomanchu.com/guides/andy-klise-3x3x3-oll-v3.pdf
```
3. Open a doc file and past the following on a new line. Then click the links to confirm that the PDFs are available:
```
- [3x3x3 speedcubing guide](/content/andy-klise-3x3x3-speedcubing-guide-v4.pdf)
- [3x3x3 speedcubing guide for lefties](/content/andy-klise-3x3x3-speedcubing-guide-v4-lefty.pdf)
- [OLL guide](/content/andy-klise-3x3x3-oll-v3.pdf)
```
4. Open a doc file and paste the following in a new line:
```md
Download the [3x3x3 speedcubing guide](/content/andy-klise-3x3x3-speedcubing-guide-v4.pdf), [3x3x3 speedcubing guide for lefties](/content/andy-klise-3x3x3-speedcubing-guide-v4-lefty.pdf), and the [OLL guide](/content/andy-klise-3x3x3-oll-v3.pdf). 
```
5. Get this error (I used `.template.md`):
```bash
./docs/template.md
SyntaxError: /template.md: Expected corresponding JSX closing tag for <p> (8:248)

   6 |       components={components}>
   7 | 
>  8 | <p>{`Download the `}<a target="_blank" href={require('!file-loader?name=assets/files/[name]-[hash].[ext]!../static/content/andy-klise-3x3x3-speedcubing-guide-v4.pdf').default}  >{`3x3x3 speedcubing guide`}</a>{`3x3x3 speedcubing guide for lefties`}</a>{`OLL guide`}</a>{`, `}<a target="_blank" href={require('!file-loader?name=assets/files/[name]-[hash].[ext]!../static/content/andy-klise-3x3x3-speedcubing-guide-v4-lefty.pdf').default}  >{`, and the `}<a target="_blank" href={require('!file-loader?name=assets/files/[name]-[hash].[ext]!../static/content/andy-klise-3x3x3-oll-v3.pdf').default}  >{`. `}</p>
     |                                                                                                                                                                                                                                                         ^
   9 |     </MDXLayout>
  10 |   )
  11 | };
 @ ./.docusaurus/registry.js 1:10885-10930 1:10775-10859
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js
```
1. You can also delete a new line from the list and get a similar error:
```md
- [3x3x3 speedcubing guide](/content/andy-klise-3x3x3-speedcubing-guide-v4.pdf) [3x3x3 speedcubing guide for lefties](/content/andy-klise-3x3x3-speedcubing-guide-v4-lefty.pdf)
- [OLL guide](/content/andy-klise-3x3x3-oll-v3.pdf)
```
will give this error:
```bash
./docs/template.md
SyntaxError: /template.md: Expected corresponding JSX closing tag for <li> (9:248)

   7 | 
   8 | <ul>
>  9 | <li parentName="ul"><a target="_blank" href={require('!file-loader?name=assets/files/[name]-[hash].[ext]!../static/content/andy-klise-3x3x3-speedcubing-guide-v4.pdf').default}  >{`3x3x3 speedcubing guide`}</a>{`3x3x3 speedcubing guide for lefties`}</a>{` `}<a target="_blank" href={require('!file-loader?name=assets/files/[name]-[hash].[ext]!../static/content/andy-klise-3x3x3-speedcubing-guide-v4-lefty.pdf').default}  ></li>
     |                                                                                                                                                                                                                                                         ^
  10 | <li parentName="ul"><a target="_blank" href={require('!file-loader?name=assets/files/[name]-[hash].[ext]!../static/content/andy-klise-3x3x3-oll-v3.pdf').default}  >{`OLL guide`}</a></li>
  11 | </ul>
  12 |     </MDXLayout>
 @ ./.docusaurus/registry.js 1:10885-10930 1:10775-10859
 @ ./node_modules/@docusaurus/core/lib/client/exports/ComponentCreator.js
 @ ./.docusaurus/routes.js
 @ ./node_modules/@docusaurus/core/lib/client/clientEntry.js
 @ multi ./node_modules/react-dev-utils/webpackHotDevClient.js ./node_modules/@docusaurus/core/lib/client/clientEntry.js
```
## Expected behavior

<!--
  How did you expect your project to behave?
  It’s fine if you’re not sure your understanding is correct.
  Write down what you thought would happen.
-->

I thought the markdown would parse normally.

## Actual Behavior

<!--
  Did something go wrong?
  Is something broken, or not behaving as you expected?
  Describe this section in detail, and attach screenshots if possible.
  Don't only say "it doesn't work"!
-->

I get a syntax error.

## Your Environment

<!-- Include as many relevant details about the environment you experienced the bug in -->

- Docusaurus version used: alpha-66
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Ubuntu WSL 18.04, Node 12.16.0
- Operating system and version (desktop or mobile): desktop, Windows build 19041.572

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

https://github.com/TheodoreChu/docusaurus-bug-report-demos/blob/main/docs/pdf-bug.md
 
<!--
  What happens if you skip this step?

  Someone will read your bug report, and maybe will be able to help you,
  but it’s unlikely that it will get much attention from the team. Eventually,
  the issue will likely get closed in favor of issues that have reproducible demos.

  Please remember that:

    * Issues without reproducible demos have a very low priority.
    * The person fixing the bug would have to do that anyway. Please be respectful of their time.
    * You might figure out the issues yourself as you work on extracting it.

  Thanks for helping us help you!
-->

## Temporary workaround
Link the pdf files on separate lines as in step 3.

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Attempt to fix #3631

Note: I didn't quite understand why the parent node content should be changed now, if it's easier and safer to change the child node (which was done).

Previous tests are passed successfully + add new test for new use case.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Unit tests (I guess).

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-mdx-loader/src/remark/transformLinks/index.js [hunk 1]
```diff
@@ -46,22 +54,13 @@ function toAssetRequireNode({node, index, parent, filePath, requireAssetPath}) {
...
-  const linkText = (node.children[0] && node.children[0].value) || '';
-  delete node.children;
-
-  parent.children.splice(index + 1, 0, {
-    type: 'text',
-    value: linkText,
-  });
-
-  parent.children.splice(index + 2, 0, {type: 'jsx', value: '</a>'});
+  } >${linkText}</a>`;
```
Comment (slorber) [inline packages/docusaurus-mdx-loader/src/remark/transformLinks/index.js:63]:
```suggestion
  }>${linkText}</a>`;
```

Wonder if we can sately remove this space here? Seems not useful to keep it and unusual?
This would modify the snapshots but should be fine

**Review by slorber — APPROVED** [review]
Thanks, LGTM

@anshulrgoyal if there's a strong reason to modify the parent node it's time to tell us :)

**Comment by anshulrgoyal** [comment]
I think it is to support children in a tag

**Comment by slorber** [comment]
> I think it is to support children in a tag

@anshulrgoyal can you give an example md snippet? not sure to understand what you mean by that but it may be worth adding an extra test case of this

**Comment by anshulrgoyal** [comment]
Something like this 

```
[![image](url)](url)

```

**Comment by slorber** [comment]
oh :D you mean an image link? didn't know it was possible to do that, but worth checking if this still works

**Comment by anshulrgoyal** [comment]
> oh, you mean an image link?
> Didn't know it was possible to do that, but worth checking if this still works

In MDX the file is converted to MDAST->HAST->MDXAST. So we can't just put link text between <a> and </a>

**Comment by lex111** [comment]
Indeed, image links do not work in the current implementation (because that use case is not covered by unit test), as well as rendering other (child) HTML tags inside the asset link (because type for all children is hardcoded as `text`).

In this PR I fixed these issues, see unit tests/snapshots for details.

I also did a small cleanup code (removed extra spaces in the output and unnecessary `slug` import , escaped `title` attribute).
So now I guess everything should be fine. @slorber please re-check this.

Note for future refactoring: instead of using string interpolation we need to come up with a clearer and better way to create `a` elements and dynamically add attributes to them.

Strange (?) thing: It seems that the handling of asset paths between `transformLinks` and `transformImage` is different (compare the body of `toAssetLinkNode` and `processImageNode` functions). For example, `@site` alias does not support in `transformImage`, that how it should be?

**Comment by anshulrgoyal** [comment]
Hi @lex111 If a child is JSX then how is it handled like:-

```
[<Button>Open</Button>](url)

```

**Comment by slorber** [comment]
Thanks @lex111 , LGTM!

Tried this in MDX playground, didn't even know it was possible 🤪 

```
[<div style={{color: "red"}}>Open</div>](http://reactnative.dev/)
```

Does your code support it currently? Looks like it support MD in link but JSX?

Also what about adding a complex example of this dogfooding page?
https://v2.docusaurus.io/examples/markdownPageExample 
This is a bit messy, we can refactor it a bit later but at least it ensures that it actually works in production :)

> For example, @site alias does not support in transformImage, that how it should be?

Yes, this is a bit different, wanted to enable @site alias for both but didn't have time and had to release an urgent fix a few releases back 😅 if you can support @site alias in the other code as well that would be great :)

**Comment by lex111** [comment]
JSX inside asset Markdown link is already supported, although I don't think anyone will use it actively, but I updated the test to make sure that it really works.

**Comment by lex111** [comment]
> Also what about adding a complex example of this dogfooding page?

Hmm, this is standard functionality that is assumed to work out of the box. I do not know which new use cases to add in the example demo page. So if you think you need to update this page, please feel free do it yourself.

**Comment by slorber** [comment]
thanks, let's merge this :)
