### PR TITLE
fix: warn unsupported languages by prismjs 

### LINKED ISSUE #1076: Don't show error messages for prismjs missing languages
## 💥 Proposal

Currently, it's possible to use `usePrism: true` to set prismjs as the syntax highlighter for all languages. However when a language that prismjs doesn't support is used, the errors are logged to console. Personally think this could be done much better.

```
 Error: Cannot find module 'prismjs/components/prism-html.min'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Function.require (/Users/kyleroach/Developer/react-native-elements/website/node_modules/docusaurus/lib/core/renderMarkdown.js:52:17)
    at Object.rules.fence (/Users/kyleroach/Developer/react-native-elements/website/node_modules/remarkable/lib/rules.js:73:37)
    at Renderer.render (/Users/kyleroach/Developer/react-native-elements/website/node_modules/remarkable/lib/renderer.js:71:39)
    at Remarkable.render (/Users/kyleroach/Developer/react-native-elements/website/node_modules/remarkable/lib/index.js:152:24)
    at MarkdownRenderer.render (/Users/kyleroach/Developer/react-native-elements/website/node_modules/docusaurus/lib/core/renderMarkdown.js:103:26)
    at toHtml (/Users/kyleroach/Developer/react-native-elements/website/node_modules/docusaurus/lib/core/renderMarkdown.js:113:43) code: 'MODULE_NOT_FOUND' }
```

References https://github.com/facebook/Docusaurus/pull/735#issuecomment-395484508

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by Shriram-Balaji**
## Motivation

Fixes #1076 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

The stacktrace errors thrown by prismjs for unsupported languages (eg: `toml`) are now logged only as a warning message instead of logging the entire stack trace. This can be tested by doing the following changes:
 1. Set `usePrism:true` in `siteConfig.js`.
 2. Modify docs/api-doc-markdown.md to render a language not supported by prismjs.
	Eg: (toml)
	```toml
		# This is a TOML document. Boom.
		title = "TOML Example"
		
		[dog]
		name = "Lucky"
		breed = "Labrador"
		
		[cat]
		name = "Fluffy"
		breed = "Siamese"
	```

3. 
```bash
	cd website
	yarn start
```

 A warning message similar to the screenshot below would be logged in the console.

prism-errors

### CODE REVIEW

File: v1/lib/core/renderMarkdown.js [hunk 1]
```diff
@@ -45,14 +47,20 @@ class MarkdownRenderer {
...
-                const language = alias[lang] || lang;
                 // Currently people using prismjs on Node have to individually require()
                 // every single language (https://github.com/PrismJS/prism/issues/593)
                 require(`prismjs/components/prism-${language}.min`);
                 return prismjs.highlight(str, prismjs.languages[language]);
               } catch (err) {
-                console.error(err);
+                if (err.code === 'MODULE_NOT_FOUND') {
+                  const unsupportedLanguageError = chalk.yellow(
+                    `Warning: language-${language} is not supported by prismjs.` +
```
Comment (endiliey) [inline v1/lib/core/renderMarkdown.js]: Let's omit the `language-` so that it will be something like

```
`Warning: ${language} is not supported by prismjs.`
```

Even better if we put different color for the language itself

Comment (Shriram-Balaji) [reply v1/lib/core/renderMarkdown.js]: @endiliey Okay, Ive made that change.

**Comment by endiliey** [comment]
Thanks ! @Shriram-Balaji
