### PR TITLE
fix: copy static image as it is if image compression fail

### LINKED ISSUE #701: Fail to copy static image during build
### Is this a bug report?

yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### Environment

Docusaurus: 1.1.3
Node: 10.1

### Steps to Reproduce

1. Use the same favicon file for both headerIcon and favicon

```
grep favicon website/siteConfig.js
  headerIcon: 'img/favicon.png',
  favicon: 'img/favicon.png',
```

2. Put the favicon file in the static directory

```
ls website/static/img
aws-icons   favicon     favicon.png
```

3.  Run the build: `yarn build`

4. Check file presence in build directory

```
ls website/build/img
aws-icons    favicon     language.svg
```

### Expected Behavior

The `favicon.png` should be there

### Actual Behavior

Everything is copied except this file.

It was working on `1.0.15`, the bug was introduced with `1.1` versions.

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Fix #701 

There is no error handling on https://github.com/facebook/Docusaurus/blob/ef80581e8ef950a0865fc7851407c672c4bbd510/lib/server/generate.js#L255-L264

If the image compression fails, it will cause the image to be missing.

Example: 
https://circleci.com/gh/facebook/Docusaurus/2846
error

The build succeed but along the line there is an unhandled promise. Causing `christopher-chedeau.jpg` and `ricky-vetter.jpg` to be missing.

missing image

This PR add a fallback functionality to copy the image as it is if the image compression fail

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

https://deploy-preview-887--docusaurus-preview.netlify.com/

## Related PRs

#654

### CODE REVIEW

File: lib/server/generate.js [hunk 1]
```diff
@@ -247,11 +247,9 @@ async function execute() {
       !commander.skipImageCompression
     ) {
       const parts = normalizedFile.split(`${sep}static${sep}`);
-      const targetDirectory = join(
-        buildDir,
-        parts[1].substring(0, parts[1].lastIndexOf(sep))
```
Comment (JoelMarcey) [inline lib/server/generate.js]: Was this always wrong? I see you removed this from your update.

Comment (endiliey) [reply lib/server/generate.js]: It's not really wrong but this is not declarative enough. I think using function from nodejs path clearly shows the intent. 

```js
const targetDirectory = path.dirname(targetFile);
```

The previous code in the below section
```js
mkdirp.sync(path.dirname(targetDirectory));
```

is wrong though. It should be
```js
mkdirp.sync(targetDirectory);
```

**Comment by endiliey** [comment]
@JoelMarcey i think it definitely help in the sense that it reduces the website loading page since image size is reduced. It's causing problem because we completely skip that image if compression is failing. Ex: #701

**Comment by endiliey** [comment]
It still fails but at least the image is now intact and image is copied to build.

Here is the error printed:
```
{ Error: Error in file: /home/circleci/docusaurus/website/static/img/christopher-chedeau.jpg

spawn /home/circleci/docusaurus/node_modules/jpegtran-bin/vendor/jpegtran ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn /home/circleci/docusaurus/node_modules/jpegtran-bin/vendor/jpegtran',
  path: '/home/circleci/docusaurus/node_modules/jpegtran-bin/vendor/jpegtran',
  spawnargs: 
   [ '-copy',
     'none',
     '-optimize',
     '-outfile',
     '/tmp/c0b1b392-9983-40e2-bc2f-dca2418d460c',
     '/tmp/aa77e0b6-cbfa-4f21-b08f-02ed65dff725' ],
  killed: false,
  stdout: '',
  stderr: '',
  failed: true,
  signal: null,
  cmd: '/home/circleci/docusaurus/node_modules/jpegtran-bin/vendor/jpegtran -copy none -optimize -outfile /tmp/c0b1b392-9983-40e2-bc2f-dca2418d460c /tmp/aa77e0b6-cbfa-4f21-b08f-02ed65dff725',
  timedOut: false }
{ Error: Error in file: /home/circleci/docusaurus/website/static/img/ricky-vetter.jpg
```

**Comment by JoelMarcey** [comment]
Bad image? Or buggy compressor?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ahmadalfy** [comment]
@JoelMarcey I think it should copy in either cases ... I didn't notice that case would happen to be honest
