### PR TITLE
fix(v2): use swizzled SearchPage component if any

### LINKED ISSUE #3379: Swizzled SearchPage is not respected
## 🐛 Bug Report

After swizzling Search component from `@docusaurus/theme-search-algolia`, the swizzled component is not rendered.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Install alpha 62
1. Create new project
1. Add Algolia settings
1. Swizzle `SeachPage` component/page
1. Modify the new `SearchPage` component/page
1. Start app
1. Visit localhost:3000/search

## Expected behavior

I expected to see the changes made in the swizzled SearchPage component/page.

## Actual Behavior

No changes were rendered.

## Your Environment

- Docusaurus version used: alpha 62
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Microsoft Edge (Chromium), latest (Aug 31, 2020)
- Operating system and version (desktop or mobile): Windows, desktop

## Reproducible Demo

Repo that includes Algolia settings and swizzled `SearchPage`: 
https://github.com/martavis/docusaurus-test-alpha62

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

In PR #3280 it was allowed to swizzle `SearchPage` component, but newly swizzled component was not taken into account when building site.
This PR fixes #3379, after that if the search page component has been changed it will be used instead of initial one.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Try swizzling the component, making changes to it, starting the site, and making sure the swizzled component is actually being used.

```
yarn swizzle @docusaurus/theme-search-algolia SearchPage
```

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-utils/src/index.ts [hunk 1]
```diff
@@ -463,3 +463,17 @@ export function reportMessage(
       );
   }
 }
+
+export function getSwizzledComponent(
+  componentPath: string,
+): string | undefined {
+  const swizzledComponentPath = path.resolve(
+    process.cwd(),
+    'src',
```
Comment (lex111) [inline packages/docusaurus-utils/src/index.ts:472]: Due to the circular dependency issue, I can't use a constant from core (`import {SRC_DIR_NAME} from '@docusaurus/core/lib/constants';`) here, so I had to use a hard-coded string `src`.

```
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @docusaurus/utils-validation -> @docusaurus/utils -> @docusaurus/core -> @docusaurus/utils-validation
```

Comment (slorber) [reply packages/docusaurus-utils/src/index.ts:472]: yes already had this issue.

I think we could have a `@docusaurus/constants` project to solve this once for all, what do you think?

File: packages/docusaurus-theme-search-algolia/src/index.js [hunk 2]
```diff
@@ -29,7 +29,10 @@ function theme(context) {
     baseUrl,
     siteConfig: {title, url, favicon},
   } = context;
-  const pagePath = path.resolve(__dirname, './theme/SearchPage/index.js');
+  const pageComponent = './theme/SearchPage/index.js';
```
Comment (slorber) [inline packages/docusaurus-theme-search-algolia/src/index.js:32]: just wondering, wouldn't using `@theme/SearchPage` work?

File: packages/docusaurus-utils/src/index.ts (hunk 1 above)
Comment (lex111) [reply packages/docusaurus-utils/src/index.ts:472]: I don't want to create new package that will include only constants, maybe we can add something else to it? But if there are no other options, then I think it's worth moving the constants into separate package.

File: packages/docusaurus-theme-search-algolia/src/index.js (hunk 2 above)
Comment (lex111) [reply packages/docusaurus-theme-search-algolia/src/index.js:32]: No, because we need resolved component path, so it will be used with `fs` further.

File: packages/docusaurus-utils/src/index.ts (hunk 1 above)
Comment (slorber) [reply packages/docusaurus-utils/src/index.ts:472]: That's a bit annoying to have too many packages that do very little, but afaik it's the only clean solution to handle this properly.

Even in core, I had to split in server-side constants / client-side constants, and needed some duplication, see also packages/docusaurus/src/client/exports/constants.ts
