### PR TITLE
fix(theme): only set classname on ul elements if they have an existing class

### LINKED ISSUE #9098: Adding empty `class` attribute to `<ul>`
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

With https://github.com/facebook/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx

We have a few `<ul>`'s on our website, in an MDX file, and this script seems to be adding an empty class attribute to them, which breaks our CSS `ul:not([class])`.

Thanks to homotechsual, the fix is:

```diff
 export default function MDXUl(props: Props): JSX.Element {
-  return <ul {...props} className={transformUlClassName(props.className)} />;
+  return <ul {...props} className={props.className ? transformUlClassName(props.className) : null} />;
 }
```

### Reproducible demo

N/A

### Steps to reproduce

1. Create a something.mdx file:

<ul>
  <li>Example</li>
</ul>

2. View the DOM in the web browser, and the `<ul>` is now `<ul class="">`.

### Expected behavior

The class attribute should not be added.

### Actual behavior

The class attribute is added, as an empty string.

### Your environment

- Public source code: N/A
- Public site URL: N/A
- Docusaurus version used: 2.4.0
- Environment name and version: Chrome 114.0.5735.134, Node.js 18.16.1
- Operating system and version: Windows 10 Enterprise

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by homotechsual**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [X] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [X] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fix #9098

### Test links

Deploy preview: https://deploy-preview-9099--docusaurus-2.netlify.app/

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx [hunk 1]
```diff
@@ -22,5 +22,5 @@ function transformUlClassName(className?: string): string {
 }
 
 export default function MDXUl(props: Props): JSX.Element {
-  return <ul {...props} className={transformUlClassName(props.className)} />;
+  return <ul {...props} className={props.className ? transformUlClassName(props.className) : null} />;
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx:25]:
```suggestion
  return <ul {...props} className={props.className ? transformUlClassName(props.className) : undefined} />;
```

Fix CI

but not sure it passes linting, this is the problem with patch-x PRs 😅

File: packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx [hunk 2]
```diff
@@ -11,7 +11,11 @@ import type {Props} from '@theme/MDXComponents/Ul';
 
 import styles from './styles.module.css';
 
-function transformUlClassName(className?: string): string {
+function transformUlClassName(className?: string): string | undefined {
+  // Fix https://github.com/facebook/docusaurus/issues/9098
+  if (typeof className === 'undefined') {
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/MDXComponents/Ul/index.tsx:16]: using typeof because if props.className is '' we probably still want to have `class=''` in the final html, although it's a weird edge-case

**Review by slorber — APPROVED** [review]
