### PR TITLE
fix(content-blog): links in feed should be absolute

### LINKED ISSUE #9136: Blog Atom/RSS feed urls should be absolute instead of relative
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

If a blog post contains internal links, when the blog post is made available via feeds (rss/atom/json), the links should be made absolute, instead of relative.

Here is an example of Json feed from my site:

```json
{
    "version": "https://jsonfeed.org/version/1",
    "title": "Announcements",
    "home_page_url": "https://komga.org/blog",
    "description": "Latest Komga announcements",
    "items": [
        {
            "id": "https://komga.org/blog/prepare-v1",
            "content_html": "<p>The future v1.0.0 will bring some breaking changes, this guide will help you to prepare for the next major version.</p><h2 class=\"anchor anchorWithStickyNavbar_LWe7\" id=\"before-upgrading\">Before upgrading<a href=\"#before-upgrading\" class=\"hash-link\" aria-label=\"Direct link to Before upgrading\" title=\"Direct link to Before upgrading\">​</a></h2><ul><li>If you run Docker, it is advisable to use the <code>0.x</code> tag instead of <code>latest</code>. You will be able to decide when you want to upgrade, especially if you are updating containers automatically.</li><li>Backup your <code>database.sqlite</code>. You can find it in the configuration directory, by default:<ul><li>on Windows: <code>%USERPROFILE%/.komga/database.sqlite</code></li><li>on Unix: <code>~/.komga/database.sqlite</code></li><li>on Docker: in the directory you mounted as <code>/config</code></li></ul></li></ul><h2 class=\"anchor anchorWithStickyNavbar_LWe7\" id=\"breaking-changes\">Breaking changes<a href=\"#breaking-changes\" class=\"hash-link\" aria-label=\"Direct link to Breaking changes\" title=\"Direct link to Breaking changes\">​</a></h2><ul><li>The minimum Java version required will be Java 17:<ul><li>If you run Komga using the <code>jar</code>, you will need to make sure your Java version is sufficient by running <code>java -version</code>.</li><li>If you run Komga using Docker, you don't need to do anything.</li></ul></li><li>The hashing algorithm for files and pages will change. Previous hashes for files and pages will be deleted. On startup, if hashing is enabled, Komga will re-hash files and pages using the new algorithm.</li><li>The default port will be changed from <code>8080</code> to <code>25600</code>:<ul><li>If you use Docker, you will need to update your container or compose configuration to expose the new port.</li><li>You may need to adjust your reverse proxy settings.</li><li>You can still change the port <a href=\"/docs/installation/configuration#server_port--serverport-port\">through configuration</a>.</li></ul></li></ul>",
            "url": "https://komga.org/blog/prepare-v1",
            "title": "Prepare for v1.0.0",
            "summary": "The future v1.0.0 will bring some breaking changes, this guide will help you to prepare for the next major version.",
            "date_modified": "2023-03-21T00:00:00.000Z",
            "author": {
                "name": "gotson",
                "url": "https://github.com/gotson"
            },
            "tags": [
                "breaking change",
                "upgrade",
                "komga"
            ]
        }
    ]
}
```

And a problematic href: `<a href=\"/docs/installation/configuration#server_port--serverport-port\">`

The generated feed should instead be generating an absolute link, ie https://komga.org/docs/installation/configuration#server_port--serverport-port

### Reproducible demo

_No response_

### Steps to reproduce

1. go to https://komga.org/blog/feed.json
2. observe incorrect href

### Expected behavior

Absolute links in href

### Actual behavior

Relative links in href

### Your environment

- Public source code: https://github.com/gotson/komga-website
- Public site URL: https://komga.org
- Docusaurus version used: 2.4.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by VinceCYLiao**
… absolute

## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fix #9136

## Test Plan

added two mdx files in dogfood docs
website/_dogfooding/_blog tests/2023-07-19-a.mdx
website/_dogfooding/_blog tests/2023-07-19-b.mdx

Inside 2023-07-19-a.mdx are three links
```md
[absolute full url](https://github.com/facebook/docusaurus)

[absolute url with implicit domain name](/tests/blog/2023/07/19/b)

[relative url](2023-07-19-b.mdx)
```
Visit [/tests/blog/feed.json](https://deploy-preview-9151--docusaurus-2.netlify.app/tests/blog/feed.json)
1st link stays untouched 
2nd link resolved as "https://docusaurus.io/tests/blog/2023/07/19/b"
3rd link also resolved as "https://docusaurus.io/tests/blog/2023/07/19/b"
Which are correct.
image

### Test links

Deploy preview:  https://deploy-preview-9151--docusaurus-2.netlify.app/blog/feed.json

## Related issues/PRs

[issue 9136](https://github.com/facebook/docusaurus/issues/9136)

### CODE REVIEW

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
The current solution is too error-prone because it includes too much custom logic. Plus it does not work with all relative links. Consider the following:

```html
<a href="another-post">link</a>
```

If the page is at `/blog/2020/09/13/current-post`, then the href should point to `/blog/2020/09/13/another-post`, not `/another-post`. I.e. the resolver needs to be aware of the current URL, not just the site's URL.

Also, I would prefer not manually joining URLs in any case. Why not `elm.attribs.href = String(new URL(elm.attribs.href, currentPageURL))`?

**Comment by VinceCYLiao** [comment]
> The current solution is too error-prone because it includes too much custom logic. Plus it does not work with all relative links. Consider the following:
> 
> ```
> <a href="another-post">link</a>
> ```
> 
> If the page is at `/blog/2020/09/13/current-post`, then the href should point to `/blog/2020/09/13/another-post`, not `/another-post`. I.e. the resolver needs to be aware of the current URL, not just the site's URL.
> 
> Also, I would prefer not manually joining URLs in any case. Why not `elm.attribs.href = String(new URL(elm.attribs.href, currentPageURL))`?

Thanks for your comments. Sorry that I miss clicked the request review button.  I'll try to provide a better solution.

**Comment by VinceCYLiao** [comment]
After reading the Nodejs's doc for the URL class, I found that the URL class itself can just handle this issue.
I have revised my code accordingly and built the website locally, and checked the hrefs in the generated feed files are resolved correctly.

@Josh-Cena  Please review at your convenience. Thank you!
 [feed.json of deploy preview](https://deploy-preview-9151--docusaurus-2.netlify.app/blog/feed.json)

**Comment by VinceCYLiao** [comment]
Sorry that I forgot to run yarn test. Didn't noticed that so many tests will fail due to the changes. I'll look into how to fix the tests if you find my solution fine.

**Comment by Josh-Cena** [comment]
I think it looks good! In fact the test changes look expected to me. I reckon you don't need to resolve paths that are just anchor links, only ones that actually point to another page. We would also need test cases (either adding a new test post file, or adding a link to the existing post file)

**Comment by VinceCYLiao** [comment]
I encountered some problems while trying to add test cases.
A relative path without leading slash will make the build command throw.

I created two files:
website/_dogfooding/_blog tests/2023-07-19-a.mdx
website/_dogfooding/_blog tests/2023-07-19-b.mdx

Code in the 2023-07-19-a.mdx:
```md
 [link](b)
```

This work correctly in browser when running yarn start:website. the relative path "b" resolved into "/tests/blog/2023/07/19/b".
But while building the website, the handleBrokenLinks function will throw. And in the Error message, the relative path "b" is resolved into "/tests/b"
image

Is this considered a bug?

**Comment by VinceCYLiao** [comment]
> I think it looks good! In fact the test changes look expected to me. I reckon you don't need to resolve paths that are just anchor links, only ones that actually point to another page. We would also need test cases (either adding a new test post file, or adding a link to the existing post file)

I have added a test case and updated the test plan. Please let me know if it's ok for you. Thanks!

**Review by Josh-Cena — CHANGES_REQUESTED** [review]
Could you add the tests to https://github.com/facebook/docusaurus/tree/main/packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website instead? No one is going to look at the feed of the dogfooding blog.

**Comment by VinceCYLiao** [comment]
I was thinking to parse the links from the feeds to check if they are correctly resolved, but found it's hard to so and maybe kind of meaningless since the links in feeds are from the object returned by the defaultCreateFeedItems function.
So my idea is to just write test case for the defaultCreateFeedItems function, checking if the full absolute path links are stay on touched while other links are correctly prefixed.
Don't know if the test makes sense for you, and if it is bad to export the defaultCreateFeedItems function just for unit test.

File: packages/docusaurus-plugin-content-blog/src/feed.ts [hunk 1]
```diff
@@ -106,6 +106,14 @@ async function defaultCreateFeedItems({
       const $ = cheerioLoad(content);
 
       const link = normalizeUrl([siteUrl, permalink]);
+
+      $(`div#${blogPostContainerID} a`).each((_, elm) => {
+        const {href} = elm.attribs;
+        if (href) {
+          elm.attribs.href = String(new URL(href, link));
+        }
+      });
```
Comment (slorber) [inline packages/docusaurus-plugin-content-blog/src/feed.ts:115]: LGTM 👍 

We will also need to convert image links to absolute, see 
https://github.com/facebook/docusaurus/issues/9136#issuecomment-1645593662

https://validator.w3.org/feed/docs/warning/ContainsRelRef.html

File: packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts [hunk 2]
```diff
@@ -196,3 +228,95 @@ describe.each(['atom', 'rss', 'json'])('%s', (feedType) => {
     fsMock.mockClear();
   });
 });
+
+describe('Test defaultCreateFeedItems', () => {
```
Comment (slorber) [inline packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts:232]: That test looks super complex to me and I don't understand why.

Just call `createBlogFeedFiles` and take a snapshot: we'll review the snapshot and validate it contains what we expect

File: packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts [hunk 3]
```diff
@@ -62,6 +68,32 @@ async function testGenerateFeeds(
...
+        const href = anchorElements.map((_, elm) => elm.attribs.href).toArray();
+        linksOfBlogPosts[post.id] = href;
+      }
+    } catch {
+      // post is a draft
+    }
+  });
+  await Promise.all(promises);
+  return linksOfBlogPosts;
+}
```
Comment (slorber) [inline packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts:95]: I don't think we need that complexity inr our tests

**Review by slorber — CHANGES_REQUESTED** [review]
Thanks

The implementation looks good. 👍 

But the way it is tested looks surprisingly complex to me, and unit tests are not passing.

We also need to absolutize image URLs.

Let me know if you need help to figure out how to test that.

**Comment by VinceCYLiao** [comment]
> Thanks
> 
> The implementation looks good. 👍
> 
> But the way it is tested looks surprisingly complex to me, and unit tests are not passing.
> 
> We also need to absolutize image URLs.
> 
> Let me know if you need help to figure out how to test that.

Thanks! I'll make the image URLs also absolutized.

Regarding the test, I'm thinking to create a new mock file which contains anchor elements with absolute/relative/anchor link, and image element with absolute/relative source URLs. And then in the test case just call createBlogFeedFiles and take a snapshot.

File: packages/docusaurus-plugin-content-blog/src/feed.ts (hunk 1 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/feed.ts]: Done. Image links now are absolutized.

File: packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts (hunk 2 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts]: I think that I don't need to add new test case; instead I just need to update the snapshot. Am I correct ?

File: packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts (hunk 3 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/__tests__/feed.test.ts]: The test case is removed

**Comment by VinceCYLiao** [comment]
Tested in local and all unit tests are passed.

File: packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/blog-with-links/index.html [hunk 4]
```diff
@@ -0,0 +1,31 @@
+<!doctype html>
```
Comment (slorber) [inline packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/blog-with-links/index.html:1]: How was this file generated?

File: packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/blog-with-links.mdx [hunk 5]
```diff
@@ -0,0 +1,22 @@
+import dino from "../static/img/docusaurus.png";
+import useBaseUrl from '@docusaurus/useBaseUrl';
+
```
Comment (slorber) [inline packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/blog-with-links.mdx:3]: ES imports are supposed to come after front matter

File: packages/docusaurus-plugin-content-blog/src/feed.ts [hunk 6]
```diff
@@ -106,6 +106,33 @@ async function defaultCreateFeedItems({
...
+            }
+            if (srcset) {
+              elm.attribs.srcset = srcset
+                .split(',')
+                .map((s) => {
+                  const [imageURL, ...descriptors] = s.trim().split(/\s+/);
+                  const newImageURL = new URL(imageURL ?? '', link).href;
+                  return [newImageURL, ...descriptors].join(' ');
+                })
+                .join(', ');
```
Comment (slorber) [inline packages/docusaurus-plugin-content-blog/src/feed.ts:130]: Looks a bit unsafe/risky, maybe introduce a dedicated lib to manipulate srcset reliably instead? see https://www.npmjs.com/package/srcset

**Review by slorber — CHANGES_REQUESTED** [review]
I don't undersand how it works anymore 😅 

@Josh-Cena do you remember what updates the `build-snap` folder exactly? Is this updated manually?

@VinceCYLiao how did this PR generate that new `src/__tests__/__fixtures__/website/build-snap/blog/blog-with-links/index.html` file?

The CI is failing and snapshots are not easy to review 😓

**Comment by Josh-Cena** [comment]
> do you remember what updates the `build-snap` folder exactly? Is this updated manually?

I think I added this part of test but I don't remember how it works either. My guess is it's manual.

File: packages/docusaurus-plugin-content-blog/src/feed.ts (hunk 6 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/feed.ts:130]: Thanks. I'll look into it and revise my code

File: packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/blog-with-links/index.html (hunk 4 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/build-snap/blog/blog-with-links/index.html:1]: I created the blog-with-links.mdx in the website/blog folder and ran yarn:build:website:blogOnly. If this is not the way how the files in __fixtures__ created, please let me know the create way to do it.

**Comment by VinceCYLiao** [comment]
> I don't undersand how it works anymore 😅
> 
> @Josh-Cena do you remember what updates the `build-snap` folder exactly? Is this updated manually?
> 
> @VinceCYLiao how did this PR generate that new `src/__tests__/__fixtures__/website/build-snap/blog/blog-with-links/index.html` file?
> 
> The CI is failing and snapshots are not easy to review 😓 Surprisingly unit tests are passing locally, but not on GitHub action 🤷‍♂️

image

Just ran the tests again and they are all passed. Sorry for the confusion and I'll look into why the tests are failing on github.

File: packages/docusaurus-plugin-content-blog/src/feed.ts (hunk 6 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/feed.ts]: Done and since latest version of srcset is pure ESM, so I have to use the previous version.

File: packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/blog-with-links.mdx (hunk 5 above)
Comment (VinceCYLiao) [reply packages/docusaurus-plugin-content-blog/src/__tests__/__fixtures__/website/blog/blog-with-links.mdx]: Order of imports are now correct. I also moved the front matter to the beginning of the file. Misplacing front matter seems to be the reason why tests failed.

**Review by Josh-Cena — APPROVED** [review]
The implementation looks great to me! Just one stylistic suggestion.

**Comment by slorber** [comment]
Hold on, I'm fixing the build-snap generation thing in another process before merging this PR

**Comment by Josh-Cena** [comment]
Note that you would also want to rebase to get rid of the extra commits
