### PR TITLE
fix(v2): don't read theme from localStorage if disableDarkMode is on

### LINKED ISSUE #2176: bug(v2): site loads dark theme if dark theme exists in localStorage even when disableDarkTheme is true
## 🐛 Bug Report

Website loads dark theme if dark theme exists in `localStorage` even when `disableDarkTheme` is `true`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Set `themeConfig.disableDarkTheme: true` in `docusaurus.config.js`
1. Run `localStorage.theme = 'dark'` in JS console. This simulates the scenario where a site previously had dark mode toggle and then it was disabled.
1. Start the site locally
1. See that the site is dark.

This is especially bad when some websites are not dark-mode compatible (that's probably why they had `disableDarkTheme: true` in the first place!

## Expected behavior

Should see light theme.

## Actual Behavior

Dark theme seen.

### PR DESCRIPTION
**Pull request by yangshun**
## Motivation

Fixes #2176 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1. Set `themeConfig.disableDarkTheme: true` in `docusaurus.config.js`
1. Run `localStorage.theme = 'dark'` in JS console. This simulates the scenario where a site previously had dark mode toggle and then it was disabled
1. Start the site locally
1. See that the site is not dark

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js [hunk 1]
```diff
@@ -20,6 +25,10 @@ const useTheme = () => {
 
   React.useEffect(() => {
     try {
+      if (disableDarkMode) {
```
Comment (yangshun) [inline packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js]: I'm not sure whether it's better to just do `return [null, () =>]` at the end instead, making guaranteeing that this hook doesn't do anything.

Comment (lex111) [reply packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js]: LGTM, but why not put the condition __before__ `try` block?
