### PR TITLE
fix(v2): force terminate building if client bundle failed

### LINKED ISSUE #2311: [V2] docusaurus build becomes idle instead of throwing an error
## 🐛 Bug Report

`docusaurus build` doesn't throw an error on a failing build which results in high idle time.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

(Write your steps here:)

1. Clone the repo https://github.com/monapasan/docusaurus-idle-when-error
2. run `npm run build`

## Expected behavior

I would expect an error to be thrown and build to be finished.

## Actual Behavior
You will see that docusaurus can't resolve a module in mdx file:
```
./docs/mdx.md
Module not found: Can't resolve '../../build/components' 
```
This then results in idle time

## Reproducible Demo

https://github.com/monapasan/docusaurus-idle-when-error

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolve #2311.

Server build uses the `WaitPlugin` plugin, which waits until a client bundle is created. This wait is infinite, so if the building of client bundle fails, the build process enters idle mode.

https://github.com/facebook/docusaurus/blob/32c1a92b17bdc347add828be97a49991c0611146/packages/docusaurus/src/webpack/server.ts#L49-L52

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

- In a MDX file try to import unresolvable dependency e.g.:

```md
---
id: mdx
title: MDX page
---

import Blah from 'Blah';

Heading...
```

Prior to this fix, the build process became idle and needed to be killed (for example, by pressing CTRL + C)

Now the build process in case of an error in the client bundle terminated immediately.

Results:

| Before (idle)  | After (forced terminated)    |
| -------- | -------- |
| снимок_2 | снимок |

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus/src/webpack/client.ts [hunk 1]
```diff
@@ -30,6 +31,26 @@ export function createClientConfig(props: Props): Configuration {
       runtimeChunk: true,
     },
     plugins: [
+      // Plugin to force terminate building if errors happened in the client bundle
```
Comment (lex111) [inline packages/docusaurus/src/webpack/client.ts]: Perhaps this tiny plugin needs to be created in a separate file or class (in same file), but not sure about it. But feel free to change that.

Comment (lex111) [reply packages/docusaurus/src/webpack/client.ts]: > fix(v2) -> chore(v2) ?

Not sure exactly how the type of commit here accurately reflects the situation...

File: packages/docusaurus/src/webpack/client.ts [hunk 2]
```diff
@@ -7,6 +7,7 @@
 import path from 'path';
 import {Configuration} from 'webpack';
 import merge from 'webpack-merge';
+import chalk from 'chalk';
```
Comment (mohrash92) [inline packages/docusaurus/src/webpack/client.ts]:
```suggestion
import chalk = require('chalk');
```
Hey great work so far, do we want to maybe import like I have suggested as its a fix shown here https://github.com/chalk/chalk/releases/tag/v3.0.0 and we are using `3.0.0`. Also we did it as part of this change https://github.com/facebook/docusaurus/pull/1985. 

I think its

Comment (lex111) [reply packages/docusaurus/src/webpack/client.ts]: Good catch, thanks, fixed :heavy_check_mark:

File: packages/docusaurus/src/webpack/client.ts [hunk 3]
```diff
@@ -4,6 +4,8 @@
  * This source code is licensed under the MIT license found in the
  * LICENSE file in the root directory of this source tree.
  */
+
+import chalk from 'chalk';
```
Comment (lex111) [inline packages/docusaurus/src/webpack/client.ts]: Although it is recommended that we use the CommonJS module format (`import chalk = require('chalk');`) to import chalk, but when using this style, tests will fail with such an error:

```
 `import =` is not supported by @babel/plugin-transform-typescript
Please consider using `import <moduleName> from '<moduleName>';` alongside Typescript's --allowSyntheticDefaultImports option.
```
It is OK?

Comment (mohrash92) [reply packages/docusaurus/src/webpack/client.ts]: Seems like this is a known limitation. That is fine then :)

File: packages/docusaurus/src/webpack/client.ts (hunk 1 above)
Comment (mohrash92) [reply packages/docusaurus/src/webpack/client.ts]: > Perhaps this tiny plugin needs to be created in a separate file or class (in same file), but not sure about it. But feel free to change that. Something like `ClientBundleCheckerPlugin`??

I feel like you are right here. It can be made a separate plugin. Don't wish to take away your thunder and all your hard work on this but I can try do that if you want? :)
