### PR TITLE
fix(v2): windows compatibility

### LINKED ISSUE #1350: Docusaurus v2: improperly escaped routes on Windows
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. `git clone` and `cd` Docusaurus repo
2. `yarn install`
3. `cd website`
4. `yarn start`

## Expected behavior

The local server will start

## Actual Behavior

A blank page shows up at localhost:3000, and the terminal says: 

> Module not found: Can't resolve '@generateddocusaurus-plugin-content-blologMetadata.json' in 'C:\Users\nebrelbug\Documents\Coding\Docusaurus\website\.docusaurus'./.docusaurus/metadata.js

## Reproducible Demo

Follow the steps to reproduce

## What I think is the issue:

If you look in `website/.docusaurus/routes.js` and `website/.docusaurus/routes.js`, you can see that many of the routes look like this: `'C:\Users\nebrelbug\Documents\Coding\Docusaurus\docs\api-commands.md'` when they should look like: `C:\\Users\\nebrelbug\\Documents\\Coding\\Docusaurus\\docs\\api-commands.md`

I'm guessing this has to do with the fact that Windows uses `\` for paths

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

Fix #1350

The problem

`import XXXXX from '@generated\this-is\my\path' is incorrect`
`import XXXXX from '@generated/this-is/my/path' is correct`

The problem

We need to escape `backslashes` for windows path.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Before

previous

After

Windows
after

Linux
linux still ok

after-fix

### CODE REVIEW

File: packages/docusaurus/lib/server/load/routes.js [hunk 1]
```diff
@@ -34,7 +34,8 @@ async function loadRoutes(pluginsRouteConfigs) {
     const importStr = isObj ? target.path : target;
     const queryStr = target.query ? `?${stringify(target.query)}` : '';
     const chunkName = generateChunkName(name || importStr, prefix);
-    return `() => import(/* webpackChunkName: '${chunkName}' */ '${importStr}${queryStr}')`;
+    const finalStr = JSON.stringify(importStr + queryStr);
```
Comment (yangshun) [inline packages/docusaurus/lib/server/load/routes.js]: What does `JSON.stringify` do here? Help escape another time?

Comment (endiliey) [reply packages/docusaurus/lib/server/load/routes.js]: Yes. Otherwise it will be `C:\User` instead of `C:\\User`

**Comment by endiliey** [comment]
V1 once faced these issues but I've mostly fixed that 😄 

I use Ubuntu on Windows so sometimes I forget that I can actually use the native 'command prompt' to test out Window bugs
