### PR TITLE
fix(v2): use remark-admonitions separately in each plugin instead of in preset only

### LINKED ISSUE #2525: [v2] unable to use theme-classic without remark-admonitions
## 🐛 Bug Report

Due to https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-classic/src/index.js#L56, you are unable to to use the `@docusaurus/theme-classic` theme without installing the `remark-admonitions` module. This shouldn't be a hard requirement.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yep

## To Reproduce

1. Create a V2 project with the following config
```
'use strict';

module.exports = {
  title: 'gulp.js',
  favicon: 'img/favicon.png',
  url: 'https://gulpjs.com/',
  baseUrl: '/',
  tagline: 'The streaming build system',
  // Used by the deployment
  organizationName: 'gulpjs',
  projectName: 'gulpjs.github.io',
  // The theme
  themeConfig: {},
  themes: ['@docusaurus/theme-classic'],
  plugins: [
    ['@docusaurus/plugin-content-docs', {
      path: '../converted-docs'
    }]
  ]
};
```
1. Try to run the project
1. See this error message
Screen Shot 2020-04-03 at 6 50 27 PM

## Expected behavior

The theme should be usable without external dependencies unless I opt-in.

## Actual Behavior

Doesn't compile and is unusable without installing the `remark-admonitions` module.

## Your Environment

- Docusaurus version used: `^2.0.0-alpha.50`
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): 10.15.1
- Operating system and version (desktop or mobile): desktop

## Reproducible Demo

None currently because I'm trying to upgrade the gulp website...

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

This PR decouples admonitions from the classic theme and preset to resolve  #2525.

Now admonitions is included for each of the two plugins separately (docs and blog), this produces some duplication of code, but the classic theme is not related with admonitions.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Admonitions should work as earlier, since the `admonitions` options in preset passed to each plugin.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-plugin-content-docs/src/index.ts [hunk 1]
```diff
@@ -119,6 +128,14 @@ export default function pluginContentDocs(
       return [...globPattern, options.sidebarPath];
     },
 
+    getClientModules() {
+      if (opts.admonitions === false) {
```
Comment (yangshun) [inline packages/docusaurus-plugin-content-docs/src/index.ts:132]: I think it's better to do

```
const modules = [];

if (opts.admonitions) {
  modules.push(...);
}

return modules;
```

File: packages/docusaurus-plugin-content-docs/src/index.ts [hunk 2]
```diff
@@ -57,13 +58,21 @@ const DEFAULT_OPTIONS: PluginOptions = {
...
+  admonitions: {},
 };
 
 export default function pluginContentDocs(
   context: LoadContext,
   opts: Partial<PluginOptions>,
 ): Plugin<LoadedContent | null> {
   const options = {...DEFAULT_OPTIONS, ...opts};
+
+  if (opts.admonitions !== false) {
```
Comment (yangshun) [inline packages/docusaurus-plugin-content-docs/src/index.ts:70]: Can just do `if (opt.admonitions) {`

Comment (lex111) [reply packages/docusaurus-plugin-content-docs/src/index.ts:70]: We cannot do this because `opts.admonitions` can be an object (even empty) or a boolean value (false).

Comment (yangshun) [reply packages/docusaurus-plugin-content-docs/src/index.ts:70]: Why not? Empty objects are not falsey

Comment (lex111) [reply packages/docusaurus-plugin-content-docs/src/index.ts:70]: From docs:

> The admonitions key will be passed as the options to remark-admonitions. Passing false will prevent the plugin from being added to MDX.

I proceeded from this sentence, because the explicit value meaning better reflects our intention. Right?

Comment (lex111) [reply packages/docusaurus-plugin-content-docs/src/index.ts]: Ah, I get it your idea, I fixed all of them.
