### PR TITLE
fix(v2): don't include 404 page in sitemaps

### LINKED ISSUE #2605: Don't include the 404 route in XML sitemaps
## 🐛 Bug Report

When testing the XML sitemaps I found that the first URL in it on our site was the 404 route:

```xml
<url>
    <loc>https://developer.yoast.com/404.html</loc>
    <changefreq>weekly</changefreq>
    <priority>0.5</priority>
</url>
```

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

(Write your steps here:)

1. I guess: open any DocuSaurus v2 XML sitemap.

## Expected behavior

The XML sitemap should only contain URLs that should return a `200` status code.

## Actual Behavior

As shown above, the `404.html` file was included, which should not be indexed.

## Your Environment

- Docusaurus version used: v2

### PR DESCRIPTION
**Pull request by RDIL**
Signed-off-by: Reece Dunham <me@rdil.rocks>

## Motivation

Fixes #2605

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

I added a test to Jest to make sure this works.

In addition, you can also look at the sitemap on v2.docusaurus.io vs the deploy preview.

### CODE REVIEW

File: packages/docusaurus-plugin-sitemap/src/createSitemap.ts [hunk 1]
```diff
@@ -16,10 +16,18 @@ export default function createSitemap(
...
   if (!hostname) {
-    throw new Error('Url in docusaurus.config.js cannot be empty/undefined');
+    throw new Error('url in docusaurus.config.js cannot be empty/undefined');
   }
 
-  const urls = routesPaths.map(
+  let finalizedRoutesPaths: string[] = [];
+  // filter through routes to exclude the 404 page
+  routesPaths.forEach((route: string) => {
+    if (route.indexOf('404') === -1) {
```
Comment (yangshun) [inline packages/docusaurus-plugin-sitemap/src/createSitemap.ts:25]: This is not the most robust method. Let's check for exact route. It's ok to do so since we are covered by tests.

File: packages/docusaurus-plugin-sitemap/src/createSitemap.ts [hunk 2]
```diff
@@ -16,10 +16,18 @@ export default function createSitemap(
...
+      finalizedRoutesPaths.push(route);
+    }
+  });
+
+  const urls = finalizedRoutesPaths.map(
```
Comment (yangshun) [inline packages/docusaurus-plugin-sitemap/src/createSitemap.ts:30]: Just combine into the existing code.

```js
const urls = routesPaths.filter(route => 
  // Filter 404 route from resulting sitemap.
  route !== '404.html' // Or some other route
).map(...)
```

**Comment by RDIL** [comment]
Alright.  Fixing now.

**Comment by RDIL** [comment]
Fixed @yangshun 😃

File: packages/docusaurus-plugin-sitemap/src/createSitemap.ts [hunk 3]
```diff
@@ -16,17 +16,19 @@ export default function createSitemap(
...
-  const urls = routesPaths.map(
-    (routesPath) =>
-      ({
-        url: routesPath,
-        changefreq: options.changefreq,
-        priority: options.priority,
-      } as SitemapItemOptions),
-  );
+  const urls = routesPaths
+    .filter((route: string) => route !== '/404.html')
```
Comment (lex111) [inline packages/docusaurus-plugin-sitemap/src/createSitemap.ts:23]: Could it be possible to create from this new constant in the according file? https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/constants.ts

https://github.com/facebook/docusaurus/blob/1f00d15c7439fdbfb37d57f0cafdaedb2b34ef41/packages/docusaurus/src/server/routes.ts#L50

Comment (RDIL) [reply packages/docusaurus-plugin-sitemap/src/createSitemap.ts:23]: We already have a constant named routesPaths

Comment (lex111) [reply packages/docusaurus-plugin-sitemap/src/createSitemap.ts:23]: I meant the value "/404.html" put in a constant.

Comment (RDIL) [reply packages/docusaurus-plugin-sitemap/src/createSitemap.ts:23]: I don't really see a point, its already a static string literal

Comment (yangshun) [reply packages/docusaurus-plugin-sitemap/src/createSitemap.ts:23]: Alexey means to reduce duplication of the string `'404.html` so if we ever change it in `src/server/routes.ts`, we don't have to change it here as well. I think the current approach is fine too as the test will fail if we change it in `src/server/routes.ts` but not here.

Comment (yangshun) [reply packages/docusaurus-plugin-sitemap/src/createSitemap.ts:23]: @RDIL I'm not sure if `route !== '/404.html'` will be true for a site a `baseUrl` which is not `/`. Can you test with a non-empty `baseUrl`? We will need to be smarter about the check and use `String.prototype.endsWith()` otherwise.

Comment (RDIL) [reply packages/docusaurus-plugin-sitemap/src/createSitemap.ts]: Fixed.

**Comment by yangshun** [comment]
Thanks!
