### PR TITLE
fix(v2): fix input losing focus on init

### LINKED ISSUE #2175: bug(v2): search bar loses focus after clicking on it after initial load
## 🐛 Bug Report

On a side note, loading the JS + style when user clicks on the search bar causes a re-render and the focus is lost. It has happened to me a few times on laptop but I didn't know why. But because of this PR I tried the search bar on mobile and it became very obvious what is happening.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Load page (load on mobile to make it even more obvious)
1. Click on search bar
1. See that focus is lost and you have to reclick on the search bar

## Expected behavior

Search bar stays in focus.

## Actual Behavior

Search bar loses focus.

demo)

## Reproducible Demo

(Paste the link to an example repo, including a `siteConfig.js`, and exact instructions to reproduce the issue.)

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

A continuation of #2178 and resolve #2175 

Fix for loss of focus in search input on all screens. Moreover, this PR fixes Algolia loading on screens up to 360px, currently the search on these screens did not work  :cry: 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

1. Load Netlify preview (try on mobile too)
1. Click on the search bar
1. See that it doesn't lose focus

### CODE REVIEW

File: packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js [hunk 1]
```diff
@@ -104,10 +101,8 @@ const Search = props => {
           {'search-bar-expanded': props.isSearchBarExpanded},
           {'search-bar': !props.isSearchBarExpanded},
         )}
-        onClick={loadAlgolia.bind(this, true)}
-        onMouseOver={loadAlgolia.bind(this, false)}
```
Comment (yangshun) [inline packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js]: Why remove `onMouseOver`? We want this as an optimization for desktop where the code starts loading as soon as the cursor hovers over.

Comment (lex111) [reply packages/docusaurus-theme-search-algolia/src/theme/SearchBar/index.js]: I get it, fixed :heavy_check_mark:
