### PR TITLE
fix(blog): authors count incorrectly rendered

### LINKED ISSUE #10427: Blog authors page bugs for authors with 0 posts
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

This page doesn't look good: https://docusaurus.io/tests/blog/authors

CleanShot 2024-08-20 at 12 19 14

There's a "0" being appended to the author's name when they haven't written anything yet. This has been noticed while upgrading the React Native website:

image

---

The author page in this case should also display something more meaningful than this, probably a message telling us the author has not written anything yet, without separator?

CleanShot 2024-08-20 at 12 24 17

---

Also, we should probably keep alignment for authors with/without images otherwise it looks messy. 

What about generating empty grey placeholders for authors that have no image?

I think we could use the initials + a randomly-generated gradient.

I'd like to avoid relying on an external service, but we can take inspiration from https://github.com/vercel/avatar to build a CSS-only solution? (see https://github.com/vercel/avatar/blob/master/utils/gradient.ts)

### Reproducible demo

_No response_

### Steps to reproduce

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by OzakIOne**
## Motivation

Fix #10427

## Test Plan

Preview

### Test links

Deploy preview: https://deploy-preview-10431--docusaurus-2.netlify.app/tests/blog/authors

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/Blog/Pages/BlogAuthorsPostsPage/index.tsx [hunk 1]
```diff
@@ -52,9 +53,21 @@ function Content({author, items, sidebar, listMetadata}: Props): JSX.Element {
...
-      <hr />
-      <BlogPostItems items={items} />
-      <BlogListPaginator metadata={listMetadata} />
+      {items.length === 0 ? (
+        <p>
+          <Translate
+            id="theme.BlogAuthorsPostsPage.Content.noPosts"
+            description="The text for authors with 0 blog post">
+            This author has not written any posts yet.
+          </Translate>
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/Blog/Pages/BlogAuthorsPostsPage/index.tsx:62]:
```suggestion
          <Translate
            id="theme.blog.author.noPosts"
            description="The text for authors with 0 blog post">
            This author hasn't written any posts yet.
          </Translate>
```

minor changes + move to blogTranslations.ts

**Review by slorber — CHANGES_REQUESTED** [review]
LGTM but you need to run a yarn command to update the translations, cf the CI test failure logs and GitHub check annotations

File: packages/docusaurus-theme-common/src/translations/blogTranslations.tsx [hunk 2]
```diff
@@ -77,3 +77,13 @@ export function BlogAuthorsListViewAllLabel(): ReactNode {
     </Translate>
   );
 }
+
+export function BlogAuthorNoPostLabel(): ReactNode {
```
Comment (slorber) [inline packages/docusaurus-theme-common/src/translations/blogTranslations.tsx:81]:
```suggestion
export function BlogAuthorNoPostsLabel(): ReactNode {
```

Let's be consistent with the id ending with an s

File: packages/docusaurus-theme-translations/locales/base/theme-common.json [hunk 3]
```diff
@@ -45,6 +45,7 @@
   "theme.blog.archive.description___DESCRIPTION": "The page & hero description of the blog archive page",
   "theme.blog.archive.title": "Archive",
   "theme.blog.archive.title___DESCRIPTION": "The page & hero title of the blog archive page",
+  "theme.blog.author.noPosts": "This author has not written any posts yet.",
```
Comment (slorber) [inline packages/docusaurus-theme-translations/locales/base/theme-common.json:48]: I suspect you didn't run the command the CI / tests tells you to run, this is not the expected result from running it.

What did you run?

**Review by slorber — CHANGES_REQUESTED** [review]

**Comment by Josh-Cena** [comment]
BTW I've been meaning to enable type-aware linting in this repo, so we could catch this type of errors, but first we need to get ts-eslint up to date.

File: packages/docusaurus-theme-translations/locales/base/theme-common.json (hunk 3 above)
Comment (OzakIOne) [reply packages/docusaurus-theme-translations/locales/base/theme-common.json:48]: `yarn jest`, what am I supposed to run ?

File: packages/docusaurus-theme-classic/src/theme/Blog/Components/Author/index.tsx [hunk 4]
```diff
@@ -83,7 +83,7 @@ export default function BlogAuthor({
                 <AuthorName name={name} as={as} />
               </MaybeLink>
             )}
-            {count && <AuthorBlogPostCount count={count} />}
+            {count !== undefined && <AuthorBlogPostCount count={count} />}
```
Comment (edwin-shdw) [inline packages/docusaurus-theme-classic/src/theme/Blog/Components/Author/index.tsx:86]: What appearance is intended? If zeros should appear in a badge wouldn't it be sufficient to just render the `AuthorBlogPostCount` no matter what?
```suggestion
            <AuthorBlogPostCount count={count} />
```
Otherwise if it shouldn't show a badge at all if there are no posts, then converting `count` to a bool would be the better alternative:
```suggestion
            {Boolean(count) !== undefined && <AuthorBlogPostCount count={count} />}
```

Comment (OzakIOne) [reply packages/docusaurus-theme-classic/src/theme/Blog/Components/Author/index.tsx:86]: Any number should appear on the badge, however count can be undefined because sometimes we use the component without rendering the count badge (like on a blog post)

File: packages/docusaurus-theme-translations/locales/base/theme-common.json (hunk 3 above)
Comment (slorber) [reply packages/docusaurus-theme-translations/locales/base/theme-common.json:48]: The tests are now passing, but you didn't run the message that the previously failing tests printed:

https://github.com/facebook/docusaurus/actions/runs/10473792292/job/29006473892?pr=10431

> Errors thrown in packages/docusaurus-theme-translations/locales/__tests__/locales.test.ts
> Summary of all failing tests
> FAIL packages/docusaurus-theme-translations/locales/__tests__/locales.test.ts
>   ● theme translations › has base messages files contain EXACTLY all the translations extracted from the theme. Please run "yarn workspace @docusaurus/theme-translations update" to keep base messages files up-to-date

I can see this because your extracted message has no description, and it only modified the base locale, not all the other localized files.

You are not supposed to enter that message manually in theme translations: it's the CLI command that it supposed to do so
