### PR TITLE
fix(create-docusaurus): give a clearer message when installation failed

### LINKED ISSUE #6083: create-docusaurus show success message even when installation failed
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

We have some npm issues atm, which showed another issue in `create-docusaurus`:

image

### Steps to reproduce

npx create-docusaurus@latest my-website classic

### Expected behavior

When successful => show success message
When it fails => show **failure** message

### Actual behavior

When successful => show success message
When it fails => show **success** message

### Your environment

Latest

### Reproducible demo

_No response_

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Fix #6083.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

File: packages/create-docusaurus/src/index.ts [hunk 1]
```diff
@@ -319,4 +317,11 @@ We recommend that you begin by typing:
 
 Happy building awesome websites!
 `);
+  } else {
+    console.error(chalk.red('Dependency installation failed.'));
+    console.log(`The site directory has been created, and you can retry by typing:
+
+  ${chalk.cyan('cd')} ${cdpath}
+  ${chalk.cyan(`${pkgManager} install`)}`);
```
Comment (sohamsshah) [inline packages/create-docusaurus/src/index.ts:325]: Is it a good idea to print just `yarn` if `pkgManager===yarn` because `yarn install` doesn't make much sense.

Comment (Josh-Cena) [reply packages/create-docusaurus/src/index.ts:325]: `yarn install` makes sense. In fact I always prefer `yarn install` to `yarn`.

Comment (sohamsshah) [reply packages/create-docusaurus/src/index.ts:325]: Ohh! That's good then. I just read `yarn` instead of `yarn install` elsewhere, that's why I commented to ask. Awesome and sorry for nitpicking; was just looking at the PR code haha :)

Comment (Josh-Cena) [reply packages/create-docusaurus/src/index.ts:325]: Yeah, thanks for the review still!

Comment (sohamsshah) [reply packages/create-docusaurus/src/index.ts:325]: Also, Josh; if there are similar beginner friendly issues; always feel free to assign and tag me! I would love to contribute too ;)

Comment (Josh-Cena) [reply packages/create-docusaurus/src/index.ts:325]: We are focused on shipping the rc release so the remaining few tasks in our todo list are getting increasingly harder :/ I'll continue to delegate easier issues to the community as soon as I can think of one, so just keep updated

File: packages/create-docusaurus/src/index.ts [hunk 2]
```diff
@@ -269,34 +269,32 @@ ${chalk.cyan('Creating new Docusaurus project...')}
...
             ...(supportsColor.stdout ? {FORCE_COLOR: '1'} : {}),
           },
         },
-      );
-    } catch (err) {
-      console.log(chalk.red('Installation failed.'));
-      throw err;
+      ).code !== 0
+    ) {
+      isInstallSuccessful = false;
```
Comment (slorber) [inline packages/create-docusaurus/src/index.ts:287]: was wondering if we couldn't abort early here? throw or `exit(1)``

That could make the workflow simpler

Comment (Josh-Cena) [reply packages/create-docusaurus/src/index.ts:287]: I don't want it to exit with 1. Installation is an optional step that the user can easily recover from. As long as we have a clear message, I think it's fine

Comment (slorber) [reply packages/create-docusaurus/src/index.ts:287]: then what about exit 0 :D as long as you bail out early the code becomes simpler

Comment (Josh-Cena) [reply packages/create-docusaurus/src/index.ts:287]: Ah, I see what you mean😄Yeah, makes sense

Comment (slorber) [reply packages/create-docusaurus/src/index.ts]: Thanks, :)

**Comment by slorber** [comment]
LGTM 👍
