### PR TITLE
fix(v2): normalize location for route matching

### LINKED ISSUE #2392: Routes including `index.html` are broken
## 🐛 Bug Report

In `v1` URLs with and without `index.html` properly route to the same page. In `v2` URLs including `index.html` will result in a "Page not found". `react-router` should use a pattern that matches both URLs.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Navigate to https://v2.docusaurus.io/docs/introduction, the page should load normally.
1. Navigate to https://v2.docusaurus.io/docs/introduction/index.html, "Page not found" is displayed.

## Expected behavior

Both https://v2.docusaurus.io/docs/introduction and https://v2.docusaurus.io/docs/introduction/index.html should take the user to the same page.

## Actual Behavior

https://v2.docusaurus.io/docs/introduction/index.html renders this:
Screenshot 2020-03-09 at 16 06 34

## Your Environment

- Docusaurus version used: 2.0.0-alpha.48
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): Node.js v10.19.0
- Operating system and version (desktop or mobile): MacOS X Catalina 10.15.2

### PR DESCRIPTION
**Pull request by rlamana**
## Motivation

Fixes #2392

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

The `PendingNavigation` component now uses a `normalizeLocation` function. I added a single file for the new function to easily add unit tests and check the proper normalization of the pathname in the location object before it is passed to react-router's `Route` components for matching:

| Original Path       |  Normalized Path  |
| ------------- |-------------|
| /docs/introduction/index.html      | /docs/introduction |
| /docs/introduction    | /docs/introduction      | 
| /docs/introduction/foo.html    | /docs/introduction/foo.html        | 
| /index.html | /  |
| / | /  |

### CODE REVIEW

**Comment by rlamana** [comment]
Just to add more information about the change: since `react-router-config`.`renderRoutes()` is being used, we can use the root `<Route>` to pass a normalized `location` object to all its `Route` descendants and force the match for locations that have `index.html`.

A location with `pathname=/docs/introduction/index.html` is transformed into `pathname=/docs/introduction` and passed to all the generated routes.

**Comment by rlamana** [comment]
@yangshun the normalized location is also used in the `preload` and `startProgressBar` functions. Even though the call to `normalize` is very, very simple, it seemed like a good optimization to just call it once when the location changes, instead of calling it multiple times. Since its value affects **rendering**, the right place for it would be the component's **state**.

Let me know what you think, I can always change the PR to call `normalize` whenever is needed instead of using the state.

**Comment by yangshun** [comment]
@rlamana I would prefer to keep things stateless if possible if they can be derived. You could memoize the values instead of putting them inside state.

**Comment by rlamana** [comment]
@yangshun makes sense. I updated the PR to memoize the `normalizeLocation` function and cache the already calculated paths.

File: packages/docusaurus/src/client/PendingNavigation.js [hunk 1]
```diff
@@ -94,7 +96,7 @@ class PendingNavigation extends React.Component {
     this.clearProgressBarTimeout();
     this.progressBarTimeout = setTimeout(() => {
       clientLifecyclesDispatcher.onRouteUpdateDelayed({
-        location: this.props.location,
+        location: this.state.location,
```
Comment (yangshun) [inline packages/docusaurus/src/client/PendingNavigation.js]: There's no `this.state.location`

Comment (rlamana) [reply packages/docusaurus/src/client/PendingNavigation.js]: :sweat_smile: I missed a reference to the old state value... Now it's fixed.

Comment (yangshun) [reply packages/docusaurus/src/client/PendingNavigation.js]: Thank you! 😄
