### PR TITLE
fix: expose empty string alt text in navbar logos

### LINKED ISSUE #7658: Navbar logos not exposing empty alt text
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

When an image is truly decorative (i.e., it doesn't add additional context or information), we can apply `alt=""` _(distinct from not supplying an `alt` attribute at all)_. This removes it from screenreader output, reducing clutter. This is especially pertinent for logos inside of links that also contain other link text, such as the typical navbar brand link. W3C's Web Accessibility Initiative's [guidance on alt text for functional images](https://www.w3.org/WAI/tutorials/images/functional/#example-2-logo-image-within-link-text) includes an example just like this, where they recommend:

> In this example, the W3C logo is used to supplement text within a link that leads to the W3C home page. The image does not represent different functionality or convey other information than that already provided in the link text, so a null (empty) value is applied, (`alt=""`), to avoid redundancy and repetition. In effect the image is a decorative adjunct or visual cue to the link text…

Prior work (#3352 and #3817) enabled Docusaurus users to provide empty strings for these `alt` properties in their configs. However, when they do so, the logos are provided alts anyways, populated with the site title. As a result, Docusaurus users are not able to meaningfully mark their logos as decorative to reduce screenreader clutter.

### Reproducible demo

https://stackblitz.com/edit/github-rvbfnk?file=docusaurus.config.js

### Steps to reproduce

1. Navigate to [repro on StackBlitz](https://stackblitz.com/edit/github-rvbfnk?file=docusaurus.config.js)
2. Check `docusaurus.config.js`, specifically the config for the navbar logo, which should have an `alt: ''` property.
3. Inspect markup for navbar logo in the preview. Verify that the image has an `alt` attribute of `"My Site"`, instead of the empty string.
4. Navigate to navbar brand link with a screenreader. Verify that the link is announced as "My Site My Site," because of the alt text duplication.

### Expected behavior

If the user supplies an empty string for the logo's `alt` (distinct from not providing an `alt` at all, or providing `undefined` or `null`), the logo should apply `alt=""`, marking it as decorative for assistive technologies. Screenreaders won't announce the logo, and navigating to the brand link should just announce the site title once.

### Actual behavior

When the user supplies an empty string for the logo's `alt` config, the `alt` attribute is being populated with the site title. This means that screenreader announcements are cluttered with redundant duplication.

### Your environment

Latest versions as used on the StackBlitz playground.
See [repro on StackBlitz](https://stackblitz.com/edit/github-rvbfnk?file=docusaurus.config.js)

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by BenDMyers**
## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Resolves #7658

Allowing users to supply `alt=""` (distinct from _no_ alt/undefined alt) for their navbar brand link logos can enable users to reduce clutter in screenreader announcements. However, as it currently stands, when an empty string is provided for a logo alt, Docusaurus falls back to the provided navbar title or the site title.

This pull request ensures that if a Docusaurus config provides `alt: ''` for a logo, that empty string is respected, so Docusaurus users can confidently mark their logos as decorative and reduce duplicated announcements.

## Test Plan

Create a fresh Docusaurus site. In the Docusaurus config, update the `navbar.logo.alt` config to be an empty string. Build the site. Verify that the logo element has `alt=""` (may show up as simply `alt` in some browser devtools).

Navigate to the brand link with a screenreader. Verify that the screenreader only announces the site title once (from the visible site title label)

### Test links

Choosing to dogfood on the main Docusaurus site's brand logo link:

Deploy preview: https://deploy-preview-7659--docusaurus-2.netlify.app/

Chrome DevTools inspecting Docusaurus brand link. The logo image element shows alt set to the empty string

## Related issues/PRs

Resolves #7658

Prior art in #3352 (which addressed #3350) and #3817 (which addressed #3816)

### CODE REVIEW

**Comment by Josh-Cena** [comment]
We don't have good unit testing infra for theme components yet, and since this is wired to the theme config, mocking the context is a bit tricky. Since there's already a dogfooding test (which I've always wanted to do anyway), I think that's not very critical.

File: packages/docusaurus-theme-classic/src/theme/Logo/index.tsx [hunk 1]
```diff
@@ -32,7 +32,7 @@ export default function Logo(props: Props): JSX.Element {
       sources={sources}
       height={logo.height}
       width={logo.width}
-      alt={logo.alt || navbarTitle || title}
+      alt={logo.alt ?? (navbarTitle || title)}
```
Comment (Josh-Cena) [inline packages/docusaurus-theme-classic/src/theme/Logo/index.tsx:35]: What do you think about the case of `alt: undefined` and `navbar: { title: "TypeScript ESLint" }`? Should we use `alt=""` as well (sounds more sensible to me)?

Comment (BenDMyers) [reply packages/docusaurus-theme-classic/src/theme/Logo/index.tsx:35]: I'm pretty much of the mindset that if any text appears in the same link as the logo, the logo should have `alt=""` - since at that point, the logo serves only to adorn that text.

Comment (BenDMyers) [reply packages/docusaurus-theme-classic/src/theme/Logo/index.tsx:35]: Sure - I'll pull that out into its own declaration though, so that way it's not all inlined.

Comment (BenDMyers) [reply packages/docusaurus-theme-classic/src/theme/Logo/index.tsx]: Updated

**Comment by Josh-Cena** [comment]
image

:/ Does this look right? I don't know if that's React's intended behavior.

**Review by Josh-Cena — APPROVED** [review]

**Comment by Josh-Cena** [comment]
Just pending CLA. I'll go to sleep and @slorber may merge it or I can merge it tomorrow morning (provided the CLA comes through at that time)

**Comment by BenDMyers** [comment]
I've submitted the CLA on my end - my "receipt":
[Meta CLA.pdf](https://github.com/facebook/docusaurus/files/8960123/Meta.CLA.pdf)

Might need some time to process on y'all's end

**Comment by Josh-Cena** [comment]
Yes, it can easily take up to hours these days... We can just wait.

**Comment by BenDMyers** [comment]
No worries!

**Comment by Josh-Cena** [comment]
Thanks! LGTM
