### PR TITLE
fix(v2): use base url to navigate to search page

### LINKED ISSUE #2827: The baseUrl is not reflected in the URL generated by SearchBar.
# The baseUrl is not reflected in the URL generated by SearchBar. 

## 🐛 Bug Report

When we input a word in the SearchBar, the page should transit to "Search results" page.  
However, the URL of this page does not reflect the `baseUrl` setting.  
For example, consider the case `url='https://xyz.github.io'`, `baseUrl='/test123/'` and a search-target-word is `apple`.  
I thinks expected generated URL should be 'https://xyz.github.io/test123/search?q=apple' but actual result is 'https://xyz.github.io/search?q=apple' so that we cannot access to "Search results" page from the Search bar.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes!

## To Reproduce
(Set `baseUrl` other than `/` beforehand.)
1. Input a word in the SearchBar and hit Enter key.
  The issue occurred. 

## Expected behavior

The generated URL should be `<url> + <baseUrl> + 'search?q=<word>'`.

## Actual Behavior

The generated URL is wrong because the URL is `<url> + '/search?q=<word>'` and does not include `baseUrl`.

## Your Environment

- Docusaurus version used: `v2.0.0-alpha.56`
- Environment name and version: Chrome `81.0.4044.138`, Node.js `v12.16.2`
- Operating system and version: Windows 10 Home

## Reproducible Demo

https://tetunori.github.io/p5.toio/
https://github.com/tetunori/p5.toio

## Notes

I've just looked at the source codes for a moment and found that, at [here](https://github.com/facebook/docusaurus/blob/master/packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js#L36), it seems this URL does not reflect `baseURL`.  
So I think we need add/change the code like below and it worked fine in my environment.  
Please confirm it.

```JavaScript
import {useHistory, useLocation} from '@docusaurus/router';
import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext'; // Add

const SEARCH_PARAM_QUERY = 'q';

function useSearchQuery() {
  const history = useHistory();
  const location = useLocation();
  const {                         // Add
    siteConfig: {baseUrl} = {},   // Add
  } = useDocusaurusContext();     // Add

  return {
    searchValue:
      (ExecutionEnvironment.canUseDOM &&
        new URLSearchParams(location.search).get(SEARCH_PARAM_QUERY)) ||
      '',
    updateSearchPath: (searchValue) => {
      const searchParams = new URLSearchParams(location.search);

      if (searchValue) {
        searchParams.set(SEARCH_PARAM_QUERY, searchValue);
      } else {
        searchParams.delete(SEARCH_PARAM_QUERY);
      }

      history.replace({
        search: searchParams.toString(),
      });
    },
    navigateToSearchPage: (searchValue) => {
      // history.push(`/search?q=${searchValue}`); // <- 🐛?
      history.push(baseUrl+`search?q=${searchValue}`);  // Changed
    },
  };
}

export default useSearchQuery;

```

### PR DESCRIPTION
**Pull request by tetunori**
## Motivation
To resolve #2827.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?
Yes.

## Test Plan
- Linted (`yarn prettier && yarn lint`).
- Tested (`yarn test`)
  - but target file did not have any tests.
- Replacing the changed file on my test site to ensure that the defect is fixed.

### CODE REVIEW

**Comment by tetunori** [comment]
Thanks for your review!
I've replaced useDocusaurusContext() with useBaseUrl().
lint/prettier/test was OK and this fix seems to work fine on my local site .
but I'm not 100% sure about how to use `useBaseUrl()` function so please re-review my new code. Thanks.
(Since this is my 1st PR in GitHub, I'm excited about your reaction!)

**Comment by tetunori** [comment]
I found a side effect and it might be caused by `useBaseUrl()`.
Other than top page, search result page URL was wrong.
For example, we are in the page '<url>/<baseUrl>/docs/intro' and search there, destination is expected as '<url>/<baseUrl>/search?q=<word>' but actual was '<url>/<baseUrl>/docs/search?q=<word>`. Please confirm `useBaseUrl()` behavior.

File: packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js [hunk 1]
```diff
@@ -7,12 +7,14 @@
...
 import {useHistory, useLocation} from '@docusaurus/router';
 import ExecutionEnvironment from '@docusaurus/ExecutionEnvironment';
+import useBaseUrl from '@docusaurus/useBaseUrl';
 
 const SEARCH_PARAM_QUERY = 'q';
 
 function useSearchQuery() {
   const history = useHistory();
   const location = useLocation();
+  const baseUrl = useBaseUrl('');
```
Comment (yangshun) [inline packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: You should use it as such - 

```js
const newPath = useBaseUrl(`search?q=${searchValue}`);
```

Comment (lex111) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: > Don’t call Hooks inside loops, conditions, or **nested functions**

Would that work? I do not think so. Therefore `siteConfig.baseUrl` is a good option.

Comment (yangshun) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: This is a hook, why would it not work?

Comment (lex111) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: Try it yourself and you will see that it does not work.

```js
    navigateToSearchPage: (searchValue) => { 
      const searchUrl = useBaseUrl(`search?q=${searchValue}`); // Not work - call hook in nested functions.
      history.push(searchUrl);
    },
```

Comment (yangshun) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: If we put it at the top level of the function scope, alongside `useLocation()` and `useHistory()`, and not in the `navigateToSearchPage()` function, would that not work? That is my suggestion.

Comment (lex111) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: Nope, this way also will not work.

Comment (tetunori) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: > Try it yourself and you will see that it does not work.
> 
> ```js
>     navigateToSearchPage: (searchValue) => { 
>       const searchUrl = useBaseUrl(`search?q=${searchValue}`); // Not work - call hook in nested functions.
>       history.push(searchUrl);
>     },
> ```
I confirmed this did not work because of the error "Invalid hook call".

Comment (tetunori) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js:17]: > If we put it at the top level of the function scope, alongside `useLocation()` and `useHistory()`, and not in the `navigateToSearchPage()` function, would that not work? That is my suggestion.

Thanks, but in the top level of the function scope, we cannot get `searchValue` defined in `navigateToSearchPage()`. So your suggestion would not work, I think.

Comment (yangshun) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js]: You're right, I failed to realize we need `searchValue`. Hmm I guess this is fine then. Mind leaving a comment in the code and why we're doing this? Could add a link to this PR :)

Comment (tetunori) [reply packages/docusaurus-theme-search-algolia/src/theme/hooks/useSearchQuery.js]: @yangshun @lex111 Thanks for your reviews, guys.
I will add the comment including this PR URL.

**Comment by tetunori** [comment]
Added link to this PR and did following tests.
- Linted (`yarn prettier && yarn lint`).
- Tested (`yarn test`)
  - but target file did not have any tests.
- Replacing the changed file on my test site to ensure that the defect is fixed.

**Comment by lex111** [comment]
@tetunori thank you!
