### PR TITLE
fix(docusaurus-utils-validation): baseUrl + routeBasePath: allow empty string, normalized as "/"

### LINKED ISSUE #8254: Plugin-content-pages preset options, 'routeBasePath' can't be ''
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Description

When I use default preset options
```shell
module.exports = {
  presets: [
    [
      '@docusaurus/preset-classic',
      {
        pages: {
          path: 'src/pages',
          routeBasePath: '',
          include: ['**/*.{js,jsx,ts,tsx,md,mdx}'],
          exclude: [
            '**/_*.{js,jsx,ts,tsx,md,mdx}',
            '**/_*/**',
            '**/*.test.{js,jsx,ts,tsx}',
            '**/__tests__/**',
          ],
          mdxPageComponent: '@theme/MDXPage',
          remarkPlugins: [require('remark-math')],
          rehypePlugins: [],
          beforeDefaultRemarkPlugins: [],
          beforeDefaultRehypePlugins: [],
        },
      },
    ],
  ],
};
```
It pointed out that `ValidationError: "routeBasePath" is not allowed to be empty`
image

### Self-service

- [X] I'd be willing to address this documentation request myself.

### PR DESCRIPTION
**Pull request by Djunnni**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation
some of packages, written about allow('') but it can be update by custom or default
so i use empty('') that is customed in [joi](https://joi.dev/api/?v=17.6.1#string) 

### Test links

Deploy preview: https://deploy-preview-_____--docusaurus-2.netlify.app/

## Related issues/PRs

fix #8254

#8255

### CODE REVIEW

File: packages/docusaurus-utils-validation/src/validationSchemas.ts [hunk 1]
```diff
@@ -96,6 +96,9 @@ export const PathnameSchema = Joi.string()
     '{{#label}} is not a valid pathname. Pathname should start with slash and not contain any domain or query string.',
   );
 
+// joi empty string not allowed by default. so using empty('') for custom use
+export const RouteBasePathSchema = Joi.string().empty('').default('');
```
Comment (slorber) [inline packages/docusaurus-utils-validation/src/validationSchemas.ts:100]: Let's wait for a decision to be made in https://github.com/facebook/docusaurus/issues/8254#issuecomment-1294681922

I'd prefer to have `allow('')` instead of `empty('')` here, and not have a default value of '' => default should applied on a case by case basis.

Eventually we could use this scema for baseUrl too (rename to PathSegmentSchema?), and normalize both baseUrl + routeBasePath to have leading/trailing slashes

Comment (Djunnni) [reply packages/docusaurus-utils-validation/src/validationSchemas.ts:100]: When i did some of test, if use `allow('')`, it return '' 

So i use empty('') then default('')

It gauarantee this case

`joi.string().allow('').default('/') => ''`
`joi.string().empty('').default('').default('/') => '/'`

`joi.string().empty('').default('/') => '/'` => this case can't gaurantee because it return ''

I found rootBasePath used '/', '', 'blogs' in this repo and then customized by default value individually

Comment (slorber) [reply packages/docusaurus-utils-validation/src/validationSchemas.ts:100]: You forgot I initially suggested to add the same code as baseurl: `.custom((value: string) => addLeadingSlash(addTrailingSlash(value))),`

Comment (Djunnni) [reply packages/docusaurus-utils-validation/src/validationSchemas.ts:100]: i also test this case you announced,
 
when i input empty string ""
`joi.string().custom((value: string) => addLeadingSlash(addTrailingSlash(value))) => throw error ` 
`joi.string().allow('').custom((value: string) => addLeadingSlash(addTrailingSlash(value)) => return ''

Comment (Djunnni) [reply packages/docusaurus-utils-validation/src/validationSchemas.ts:100]: example
스크린샷 2022-10-28 오후 7 35 03
스크린샷 2022-10-28 오후 7 38 10

**Comment by slorber** [comment]
Did some changes to the PR

- `baseUrl` now allows `''`, normalized as `'/'`, and keep its login of adding leading/trailing slashes
- `routeBasePath` now allows `''`, normalized as `'/'`, and only add a leading slash


I didn't want to normalize adding a trailing slash to `routeBasePath` (for now) because it is likely to lead to behavior changes, particularly for parent routes such as `/docs`. 

Maybe this is possible to normalize technically, but it would require more tests to be sure.
