### PR TITLE
fix(website): fix showcase search input

### LINKED ISSUE #9248: unable to search or type the text input focus changes while typing
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

unable to search or type the text input focus changes while typing 

https://github.com/facebook/docusaurus/assets/68702055/0fb90d78-1aa4-491e-8b7e-9a2da67674b0

### Reproducible demo

_No response_

### Steps to reproduce

go to the website and click on showcase and start typing on search for site name

### Expected behavior

able to write the text on enter or after  2sec 

### Actual behavior

able to write the text after  that search will happen

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by biplavmz**
fix #9248 

Hii @slorber please  look into this.

### CODE REVIEW

File: website/src/pages/showcase/index.tsx [hunk 1]
```diff
@@ -328,11 +325,19 @@ function ShowcaseCards() {
...
       <main className="margin-vert--lg">
         <ShowcaseHeader />
         <ShowcaseFilters />
+        {filteredUsers.length !== 0 && (
+          <div
+            style={{display: 'flex', marginLeft: 'auto'}}
+            className="container">
+            <SearchBar />
+          </div>
+        )}
```
Comment (slorber) [inline website/src/pages/showcase/index.tsx:340]: I don't think this is good. The `<SearchBar>` should remain the same either if there are results or not.

**Review by slorber — CHANGES_REQUESTED** [review]
LGTM apart the no results case: we should also be able to keep typing in the input.

Also, please fix the lint errors
