### PR TITLE
fix(v2): use page title from config if not set

### LINKED ISSUE #4549: Title tag not defaulted to just config title if no page title
## 🐛 Bug Report

When a Layout component doesn't have a `title` prop passed in, the site title set in `docusaurus.config.js` isn't used as a fallback.

This only happens when building and serving as in prod, just calling `npm serve` doesn't cause this issue
This seems to be a recently introduced bug, as it worked in 2.0.0-alpha.70

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Install the default docusaurus site `npx @docusaurus/init@latest init my-website classic`
2. Edit `src/pages/index.js` by removing the `title` param from the `Layout` component
3. Serve the site with the build flag `npm run serve -- --build --port 80 --host 0.0.0.0`
4. Check the <title> tag in the <head> of the home page; it should be empty

## Expected behavior

I expect the global site title, set in `docusaurus.config.js`, to be used as a fallback. Essentially the page title and the | character just aren't included if they aren't given.

This is how it worked in 2.0.0-alpha.70, and given the [code here](https://github.com/facebook/docusaurus/blob/bfe52cdae32c870cef0cd5249e47fc04253bc234/packages/docusaurus-theme-common/src/utils/generalUtils.ts#L12) it seems intended to work this way.

## Actual Behavior

No title is set on the page.

This can hurt SEO performance for a site, cause the browser tab name to be the raw URL instead of human friendly text, and break social media cards when sharing the site.

## Your Environment

- Public source code: https://codesandbox.io/s/cranky-cdn-scjmr?file=/src/pages/index.js
- Public site url: https://csb-scjmr.netlify.app/
- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
- Operating system and version (desktop or mobile):

## Reproducible Demo

(same links as public source code and public site url above)
source: https://codesandbox.io/s/cranky-cdn-scjmr?file=/src/pages/index.js
webpage: https://csb-scjmr.netlify.app/
default `docusaurus.config.js` file

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Fixes #4549

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Try remove `title` prop from `Layout` component of any page and make sure that title from config has been used.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/Seo/index.tsx [hunk 1]
```diff
@@ -17,13 +18,14 @@ export default function Seo({
...
 }: Props): JSX.Element {
-  const metaTitle = useTitleFormatter(title);
-  const metaImageUrl = useBaseUrl(image, {absolute: true});
+  const {image: defaultImage} = useThemeConfig();
+  const pageTitle = useTitleFormatter(title);
+  const pageImage = useBaseUrl(image || defaultImage, {absolute: true});
 
   return (
     <Head>
-      {title && <title>{metaTitle}</title>}
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/Seo/index.tsx:25]: oh I see, had a hard time figuring out what the problem was :D

**Comment by slorber** [comment]
LGTM thanks 👍
