### PR TITLE
Use absoluteURL instead of relativeURL for next/prev links

### LINKED ISSUE #780: Trailing slashes in link causing next/prev buttons to break
### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### Environment

Docusaurus 1.1.5 or 1.2.0

### Steps to Reproduce

https://github.com/babel/website/issues/1693

### Expected Behavior

Links work

### Actual Behavior

Links don't work

### Reproducible Demo

I think Babel fixed the issue by removing the `/` from the links in https://github.com/babel/website/issues/1693

### PR DESCRIPTION
**Pull request by endiliey**
## Motivation

- Fixes #780 & https://github.com/babel/website/issues/1693

Our docs prev/next button is build with relative path in mind. But relative path is really `relative`

If our current url is https://babeljs.io/docs/en/babel-plugin-transform-runtime
`<a href='babel-register'/>` will translate to https://babeljs.io/docs/en/babel-register

If our current url is https://babeljs.io/docs/en/babel-plugin-transform-runtime/
`<a href='babel-register'/>` will translate to https://babeljs.io/docs/en/babel-plugin-transform-runtime/babel-register which is wrong

The fix is to use absolute url 😄 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan
Before
Go to https://docusaurus.io/docs/en/installation/ (notice the ending slash `/`) and click `previous/next` button, 404 page
before

After
Go to http://localhost:3000/docs/en/installation/ (notice the ending slash `/`) and click `previous/next` button, no problem
after

### CODE REVIEW

File: lib/core/DocsLayout.js [hunk 1]
```diff
@@ -47,7 +47,8 @@ class DocsLayout extends React.Component {
         description={content.trim().split('\n')[0]}
         language={metadata.language}
         version={metadata.version}
-        metadata={metadata}>
+        metadata={metadata}
+        removeTrailingSlash={true}>
```
Comment (JoelMarcey) [inline lib/core/DocsLayout.js]: Would there be time when this would ever be set to `false`? Just wondering if we need a prop at all and we just always remove the trailing slash?

**Comment by endiliey** [comment]
@yangshun @JoelMarcey 

Actually we always use relative url for next/prev in sidebar.

**Docusaurus 1.2.0**
https://github.com/facebook/Docusaurus/blob/3755522681bc5ea805be4aa6b06d5dfdf3226ec1/lib/core/DocsLayout.js#L84-L90

**Docusaurus < 1.2.0**
https://github.com/facebook/Docusaurus/blob/aee255219bedc97b55048cdb4703742cbb7c247e/lib/core/DocsLayout.js#L70-L73

I do feel my solution of removing trail slashes is a bit hacky though 😃.

Anyway, I'm changing it to use absolute URL with my latest commit so this bug will no longer exist 👍

**Comment by yangshun** [comment]
> Actually we always use relative url for next/prev in sidebar.

@endiliey Do we have next/prev in sidebar? What I mean is that in the left sidebar nav, we use absolute URLs, which is the approach I feel is better and we should do that for the next/prev buttons within the doc page.

**Comment by endiliey** [comment]
@yangshun Sorry. I mean next/prev button in docs 😢 

Anyway, changes updated. We now use absolute URL
