### PR TITLE
fix(v2): dynamic dark mode detection without toggle widget

### LINKED ISSUE #3876: Automatic detection of dark mode not working when disableSwitch=true
## 🐛 Bug Report

Assuming `colorMode.respectPrefersColorScheme` is set to true,  
- when `colorMode.disableSwitch` is `false`, the color theme changes dynamically when the OS setting is changed, without requiring a full page reload.
- when `colorMode.disableSwitch` is `true`, this behavior doesn't work. Instead, the user has to reload the page for the correct color theme to kick in.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Set `colorMode.respectPrefersColorScheme` to `true`
2. Set `colorMode.disableSwitch` to true
3. Make sure your localStorage is empty
4. Change your OS color theme preference, the color theme of Docusaurus is not dyamically updated 

## Expected behavior

The color theme should change dynamically.

## Actual Behavior

[🎥 observed behavior](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-off.webm)  
[🎥 behavior when toggle is on (for comparison)](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-on.webm)
[🎥 expected behavior](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-off_fixed.webm)

## Your Environment

N/A

## Reproducible Demo

N/A

### PR DESCRIPTION
**Pull request by hmil**
## Motivation

Dynamic automatic dark mode detection is disabled when the manual switch is hidden. But I want to enjoy the benefits of automatic dark-mode switching without showing the manual toggle.

See details in #3876 

close #3876 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

With the following config:

```
    colorMode: {
      defaultMode: 'light',
      disableSwitch: true, // Don't show manual switch
      respectPrefersColorScheme: true, // But respect user preference!
    },
```

[🎥 before this fix](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-off.webm)  
[🎥 after this fix](https://files.hmil.fr/cloud/docusaurus_dark-mode_toggle-off_fixed.webm)

Not shown in the screencasts: Currently, the correct color theme gets applied but only if you do a hard reload of the page. The difference that this fix makes is that you don't have to reload the page anymore.

## Related PRs

none

### CODE REVIEW

**Comment by hmil** [comment]
Please re-run the CLA check.

File: packages/docusaurus-theme-classic/src/theme/hooks/useTheme.ts [hunk 1]
```diff
@@ -38,7 +38,7 @@ const storeTheme = (newTheme) => {
 
 const useTheme = (): useThemeReturns => {
   const {
-    colorMode: {disableSwitch = false},
+    colorMode: {disableSwitch = false, respectPrefersColorScheme = true},
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/hooks/useTheme.ts:41]:
```suggestion
    colorMode: {disableSwitch, respectPrefersColorScheme},
```

Comment (slorber) [reply packages/docusaurus-theme-classic/src/theme/hooks/useTheme.ts:41]: removing default args in JSX because the theme validation/normalization ensure these attributes are never undefined

**Comment by slorber** [comment]
thanks, that makes sense!
