### PR TITLE
fix(v2): unbreak adding of custom HTML metadatas

### LINKED ISSUE #4868: themeConfig `metadatas` field possibly not working in beta.0
## 🐛 Bug Report

We've got the Redux docs sites configured to show minimal-sized social media previews:

```js
  themeConfig: {
    metadatas: [{ name: 'twitter:card', content: 'summary' }],
    // etc
  }
```

Today I've been merging in the PRs that upgraded us from versions around `alpha.72` or so to `beta.0`.

In the process, I noted that the new sites are showing a different social media preview format, whereas the main RTK site (which has not yet been updated) is still showing the desired smaller preview:

image

This suggests to me that the beta or one of the last alphas may have somehow stopped including the `metadatas` field.  If I look at the Redux core "Getting Started" page now, with `beta.0`, I see these headers:

image

whereas the Redux Toolkit "Getting Started" page, which has not yet been redeployed and updated, shows these headers:

image

and both of them have the same `metadatas` configuration in their config file.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

Unconfirmed, but likely:

-  Create a `docusaurus.config.js` with:

```js
  themeConfig: {
    metadatas: [{ name: 'twitter:card', content: 'summary' }]
  }
```

- Install Docusaurus 2 `alpha.72` or similar alpha
- Confirm that the correct `'twitter:card'` header is displayed in the page
- Update to `beta.0` and rebuild
- Confirm that the incorrect `large_image_summary` header is included instead

## Expected behavior

The Twitter image format specified `metadatas` would used, as it has been

## Actual Behavior

The specified Twitter format was not used and the header results in the wrong social media preview size

## Your Environment

I see the bug in the currently deployed Redux core and React-Redux docs sites (https://redux.js.org,  https://react-redux.js.org).

As a specific example, these were the React-Redux upgrade PRs:

- https://github.com/reduxjs/react-redux/pull/1714
- https://github.com/reduxjs/react-redux/pull/1724

Used Docusaurus version: `2.0.0-beta.0`

## Reproducible Demo

Skipping for the moment because it's late and I need to call it a night.

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolve #4868

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Make sure that on the preview site metadata key named `twitter:card` has custom value `summary` (not "summary_large_image", which is default value).

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/Layout/index.tsx [hunk 1]
```diff
@@ -43,6 +45,18 @@ function Layout(props: Props): JSX.Element {
       </div>
 
       {!noFooter && <Footer />}
+
+      <Head
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/Layout/index.tsx:49]: I don't feel like it is a good solution.

If we put this here, this means users won't be able to override global site config.metadatas by using sizzling

To me, the problem is related to having `{pageImage && <meta name="twitter:card" content="summary_large_image" />}` in the Seo component.

DocItem uses Seo in a nested way, so when declaring its image, it overrides the site global `twitter:card` meta by mistake.

I think hardcoding the `twitter:card` in LayoutHead is a safer solution that should also work, and would allow users to override it globally with site config and also on a page-by-page basis with sizzling

**Review by slorber — CHANGES_REQUESTED** [review]
I would rather move `<meta name="twitter:card" content="summary_large_image" />` to `LayoutHead`

File: packages/docusaurus-theme-classic/src/theme/Layout/index.tsx (hunk 1 above)
Comment (lex111) [reply packages/docusaurus-theme-classic/src/theme/Layout/index.tsx]: I see, you are right, fixed this.

File: website/docusaurus.config.js [hunk 2]
```diff
@@ -305,7 +305,7 @@ const isVersioningDisabled = !!process.env.DISABLE_VERSIONING || isI18nStaging;
       additionalLanguages: ['java'],
     },
     image: 'img/docusaurus-soc.png',
-    // metadatas: [{name: 'twitter:card', content: 'summary'}],
+    metadatas: [{name: 'twitter:card', content: 'summary'}],
```
Comment (slorber) [inline website/docusaurus.config.js:308]:
```suggestion
    // metadatas: [{name: 'twitter:card', content: 'summary'}],
```

This works so will revert our site setting before merging

**Review by slorber — APPROVED** [review]
