### PR TITLE
fix(theme-classic): make React elements in pre render correctly

### LINKED ISSUE #6156: <strong> Tag Doesn't Shows Properly in <pre> Block
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

I Write a Test Case below
<pre><strong>输入：</strong>a = "abcd", b = "cdabcdab"
<strong>输出：</strong>3
<strong>解释：</strong>a 重复叠加三遍后为 "ab<strong>cdabcdab</strong>cd", 此时 b 是其子串。
</pre>
```html
<pre>
  <strong>输入：</strong>a = "abcd", b = "cdabcdab"
  <strong>输出：</strong>3
  <strong>解释：</strong>a 重复叠加三遍后为 "ab<strong>cdabcdab</strong>cd", 此时 b 是其子串。
</pre>
```
As we can see blow, Github shows correctly
but if this block appears in a docusaurus MarkDown file when build a website
it appears like blow
image
<pre tabindex="0" class="prism-code language-undefined codeBlock_rtdJ thin-scrollbar" style="color: rgb(57, 58, 52); background-color: rgb(246, 248, 250);"><code class="codeBlockLines_1zSZ"><span class="token-line" style="color: rgb(57, 58, 52);"><span class="token plain">[object Object]a = "abcd", b = "cdabcdab"[object Object]3[object Object]a 重复叠加三遍后为 "ab[object Object]cd", 此时 b 是其子串。</span><br></span></code></pre>
which turns `<strong>` tag into [object Object]

### Steps to reproduce

write a markdown file includes  `<strong>` tag in a `<pre>` tag
```html
<pre>
  <strong>输入：</strong>a = "abcd", b = "cdabcdab"
  <strong>输出：</strong>3
  <strong>解释：</strong>a 重复叠加三遍后为 "ab<strong>cdabcdab</strong>cd", 此时 b 是其子串。
</pre>
```

### Expected behavior

Correct Content

### Actual behavior

Incorrent

### Your environment

- Public source code: https://github.com/DawnMagnet/algorithm-station
- Public site URL:https://dawnmagnet.github.io/algorithm-station
- Docusaurus version used: latest
- Environment name and version (e.g. Chrome 89, Node.js 16.4): nodejs 14
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): travis-ci

### Reproducible demo

_No response_

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Fix #6156. It seems the solution in #3749 was not good enough since it doesn't take React elements into account; this is further traced back to #1584 where Endi decided to unwrap the `pre` when the children is a React element. However that would not be the user's intention, because GitHub treats `<pre>` as code blocks:

<pre>
<strong>hey</strong>
</pre>

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

https://deploy-preview-6177--docusaurus-2.netlify.app/tests/pages/code-block-tests

| Before | After |
|--------|-------|
| image | image |

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx [hunk 1]
```diff
@@ -33,40 +33,25 @@ const MDXComponents: MDXComponentsObject = {
...
+    const shouldBeInline = React.Children.toArray(props.children).every(
+      (el) => typeof el === 'string' && !el.includes('\n'),
     );
-  },
-  a: (props) => <Link {...props} />,
-  pre: (props) => {
-    const {children} = props;
 
-    // See comment for `code` above
-    if (isValidElement(children) && isValidElement(children?.props?.children)) {
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx:55]: wouldn't it be better to just improve this test?

File: packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx [hunk 2]
```diff
@@ -49,13 +49,44 @@ export default function CodeBlock({
   const codeBlockTitle = parseCodeBlockTitle(metastring) || title;
   const prismTheme = usePrismTheme();
 
-  // In case interleaved Markdown (e.g. when using CodeBlock as standalone component).
+  // <pre> tags in markdown map to CodeBlocks and they may contain JSX children.
+  // When the children is not a simple string, we just return a styled block without actually highlighting.
+  if (React.Children.toArray(children).some((el) => isValidElement(el))) {
+    return (
+      <Highlight
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx:56]: what is the purpose of using the Highlight component in this case? is it only to share styling?

Should we also add the "copy" button in such case?

Comment (Josh-Cena) [reply packages/docusaurus-theme-classic/src/theme/CodeBlock/index.tsx:56]: Yes, it's for styling because the background color & the font comes from the Prism renderer's theme/

I don't think it'll be very easy to add the copy button, because we just want to copy plain text, and extracting plain text from the deeply nested React children is quite tedious.

File: packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx (hunk 1 above)
Comment (Josh-Cena) [reply packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx:55]: I simply don't think it's ever justified to unwrap the `pre` or `code` element... Users put it there for a reason and we have to make it render something they expect

Comment (slorber) [reply packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx:55]: 👍 agree, was just a random though
