### PR TITLE
fix(v2): parse headings directly after h1 properly

### LINKED ISSUE #4634: First Markdown heading directly following a h1 Markdown heading is rendered as <p>
## 🐛 Bug Report

A Markdown heading directly following a h1 Markdown heading at the top of the file is rendered as a paragraph.

This seems to only occur when the h1 Markdown heading is the first non-frontmatter content in the file, and is directly followed by another Markdown heading.

Separate title frontmatter does not affect the bug; however, including any content before the initial heading, or directly after (including imports, which are not rendered in the resultant static page) would result in the bug not appearing.

https://codesandbox.io/s/determined-cray-mvy4t?file=/docs/tutorial-extras/test/index.md

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

https://codesandbox.io/s/determined-cray-mvy4t?file=/docs/tutorial-extras/test/index.md

1. fork the CodeSandbox template / create new Docusaurus site
2. add a heading directly below the h1 heading for a Markdown page

## Expected behavior

The markdown renders properly

## Actual Behavior

The heading is rendered as a paragraph instead.

```md
# h1

## h2

### h3
```

image
image

<br/>

```md
# h1

import Tabs from '@theme/Tabs';

## h2

### h3
```
image

## Your Environment

Docusaurus version: 2.0.0-alpha.73
https://codesandbox.io/s/determined-cray-mvy4t?file=/docs/tutorial-extras/test/index.md

## Reproducible Demo

CodeSandbox: 
https://codesandbox.io/s/determined-cray-mvy4t?file=/docs/tutorial-extras/test/index.md

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Should fix #4634.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Suppose we have doc without defined title in frontmatter:

```
---
id: test
---

# Title

## Second heading
```

Results:

| Before   | After    |
| -------- | -------- |
| image | image |

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-utils/src/markdownParser.ts [hunk 1]
```diff
@@ -86,7 +86,7 @@ export function parseMarkdownContentTitle(
 
   const content = contentUntrimmed.trim();
 
-  const regularTitleMatch = /^(?<pattern>#\s*(?<title>[^#\n]*)+\s*#*[\s\r]*?\n*?)/g.exec(
+  const regularTitleMatch = /^(?<pattern>#\s*(?<title>[^#\n]*)+[ \t]*#?\n*?)/g.exec(
```
Comment (slorber) [inline packages/docusaurus-utils/src/markdownParser.ts:89]: Thanks, that seems to work but I don't understand why 😅 can you explain me?

Also, just thought about it, but we should probably do something for the `{#headingId}` syntax, as the cli will add it to h1 headings too

Comment (lex111) [reply packages/docusaurus-utils/src/markdownParser.ts:89]: Not sure if I can do it better than just showing demo link on [regex101](https://regex101.com/r/BqBd7D/1).

We are interested in first-level heading, so next h2 with explicit id will be parsed as expected.
