### PR TITLE
Don't throw if a doc hasn't been versioned yet

### LINKED ISSUE #450: Versioning a new doc is broken
If you add a new doc to a versioned site, the new doc is not seen and an error is thrown.

### Is this a bug report?

Yes.

### Have you read the [Contributing Guidelines](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md)?

Yes.

### Environment

Docusaurus 1.0.6 

(and confirmed it happens in Docusaurus 1.0.5)

### Steps to Reproduce

1. Have some docs in your `docs` folder
2. `npm run version 1.0.0`
3. Add a new doc to the `docs` folder
4. `npm run version 2.0.0`

### Expected Behavior

Version 2.0.0 is created.

### Actual Behavior

```
Error: Document with id 'doc6' was requested but no document with that id could be located.
    at docVersion (/Users/joelm/dev/docusaurus-demo/website/node_modules/docusaurus/lib/server/versionFallback.js:136:11)
    at Object.diffLatestDoc (/Users/joelm/dev/docusaurus-demo/website/node_modules/docusaurus/lib/server/versionFallback.js:168:15)
    at files.forEach.file (/Users/joelm/dev/docusaurus-demo/website/node_modules/docusaurus/lib/version.js:92:24)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/Users/joelm/dev/docusaurus-demo/website/node_modules/docusaurus/lib/version.js:69:7)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

### Reproducible Demo

See steps above.

### PR DESCRIPTION
**Pull request by JoelMarcey**
Instead of throwing, return `null` because that means we have a
new doc in our versioning sequence

(Also, cleaned up a bit of code as I researched this)

Fixes #450

## Motivation

We had a showstopping bug where versioning would not work if you tried to add a new file to the documentation set.

## Test Plan

Versioned a set of docs as 1.0.0
Added a new doc to the master set
Ran

```
npm run version 2.0.0
```

The new doc was part of version 2.0.0

## Related PRs

N/A

### CODE REVIEW

File: lib/version.js [hunk 1]
```diff
@@ -96,8 +96,7 @@ files.forEach(file => {
   metadata.original_id = metadata.id;
   metadata.id = 'version-' + version + '-' + metadata.id;
 
-  const targetFile =
-    CWD + '/versioned_docs/version-' + version + '/' + path.basename(file);
+  const targetFile = versionFolder + '/' + path.basename(file);
```
Comment (JoelMarcey) [inline lib/version.js]: `versionFolder` is defined above as:

`const versionFolder = CWD + '/versioned_docs/version-' + version;`

So might as well not repeat the same full path again.

**Comment by iRoachie** [comment]
This fix enables the `version` script to run correctly. However it still throws on `build` if the newly created document is specified in the sidebar.

Here's the output: 
[output.txt](https://github.com/facebook/Docusaurus/files/1731051/output.txt)

Whatever process generates `docusaurus/lib/core/metadata.js`, it doesn't include the new files added.

**Comment by JoelMarcey** [comment]
@iRoachie and I discussed this on our [Discord channel](https://discord.gg/docusaurus). It looks like the `build` problem is coming down to how @iRoachie was naming his versions.

```
[
  "1.0.0-beta2",
  "0.19"
]
```

So we are bugging out parsing these somehow. We are looking to see what is going on.

**Comment by iRoachie** [comment]
Video showing the creation process and the resulting bug. https://www.useloom.com/share/5bcc2a1575694d76b034af9ad1b2d116

**Comment by JoelMarcey** [comment]
I have a fix for the other raised issue here. I am going to send that in another PR. 

I am going to land this PR to make any revert easier, if needed.
