### PR TITLE
fix(v2): render escaped HTML entities inside code properly

### LINKED ISSUE #4534: Pipe + other character inside non-top-level <code> block renders as plain text
## 🐛 Bug Report

When in a non-HTML context (that is, no top-level HTML tag exists), escaping a single pipe within a `<code>` tag works as expected, but adding any other characters causes the contents of the `<code>` tag to render as plain text (not as code).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

https://codesandbox.io/s/docusaurus-issue-demo-zhgzo
https://zhgzo.sse.codesandbox.io/docs/#problem-table

Create a table with a `<code>` block containing two instances of the vertical pipe escape code (`&#124;`). The sandbox has various examples of what renders correctly and what doesn't.

## Expected behavior

I expect it to render as below:

| Code                      | Words       |
| ------------------------- | ----------- |
| `hello`                   | hello       |
| <code>&#124;</code>       | Single pipe |
| <code>&#124;&#124;</code> | Double pipe |

## Actual Behavior

It renders as below instead:

| Code                      | Words       |
| ------------------------- | ----------- |
| `hello`                   | hello       |
| <code>&#124;</code>       | Single pipe |
| \|\| | Double pipe |

## Your Environment

- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0): CodeSandbox + node 14, windows 10 + node 14
- Operating system and version (desktop or mobile): Desktop

## Reproducible Demo

https://codesandbox.io/s/docusaurus-issue-demo-zhgzo
https://zhgzo.sse.codesandbox.io/docs/#problem-table

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Fixes #4534

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Preview - https://deploy-preview-4598--docusaurus-2.netlify.app/examples/markdownPageExample#pipe

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx [hunk 1]
```diff
@@ -14,17 +14,28 @@ import type {MDXComponentsObject} from '@theme/MDXComponents';
 const MDXComponents: MDXComponentsObject = {
   code: (props) => {
     const {children} = props;
-    if (typeof children === 'string') {
```
Comment (lex111) [inline packages/docusaurus-theme-classic/src/theme/MDXComponents/index.tsx:17]: This line of code causes current bug because HTML entities come as an array of strings, not a regular string.

**Comment by slorber** [comment]
thanks 👍 LGTM
