### PR TITLE
fix(core): conditionally include `hostname` parameter when using…

### LINKED ISSUE #8202: Docusaurus chooses port 3000 even if it is busy
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

On macOS, consider the following script `server.js`:

```js
const http = require("http");

const port = 3000;

const requestListener = function (req, res) {
    res.writeHead(200);
    res.end("My first server!");
};

const server = http.createServer(requestListener);

server.listen(port,  () => {
    console.log(`Server is running on http://localhost:${port}`);
});
```

Run it using `node server.js`.
Then start a Docusaurus project (running on v2.1.0 in my case). The documentation server will start on port 3000, although it is busy. If you then open Docusaurus in Chrome:

image
it opens my server.

however, if I use curl, I get the docusaurus page!

Screenshot 2022-10-11 at 11 52 58

If my server passes a host:

```diff
- server.listen(port,  () => {
+ server.listen(port, "localhost",  () => {
```

then Docusaurus will correctly identify that the port is busy and asks if I want to choose another port. Nonetheless I see it as a bug in Docusaurus or one of it's dependencies.

**Possible solution**

Although used by less people, this logic for finding a free port works now in Remotion without bug reports coming in: https://github.com/remotion-dev/remotion/blob/main/packages/renderer/src/get-port.ts

I am happy to chat on Discord how to investigate it together!

### Reproducible demo

_No response_

### Steps to reproduce

As above

### Expected behavior

Busy port detection kicks in and asks if a different port should be used

### Actual behavior

Server gets started and a conflict is created

### Your environment

- Docusaurus version used: v2.1.0
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Node 16.7
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): macOS

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by jack-robson**
… detect port

- Skip adding the `hostname` parameter if the host is "localhost".

## Pre-flight checklist

- [X] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [ ] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [ ] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #0000) and the maintainers have approved on my working plan.

## Motivation

Fixing bugs for Hacktoberfest.

This closes #8202  

Don't think it warrants a unit test for this, but LMK if you disagree.

## Test Plan

**How do you know this change has worked?**

Previously, if user starts a node server using 

```
const http = require("http");

const port = 3000;

const requestListener = function (req, res) {
  res.writeHead(200);
  res.end("My first server!");
};

const server = http.createServer(requestListener);

server.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
```

And they were to start a docusaurus project, it would not detect the above script running on 3000, and therefore start docusaurus on 3000 too.

The workaround before this PR was to specifically add the "localhost" host property into the other apps code:

`server.listen(port, "localhost", () => {`

But this PR avoids the user having todo that, and still supports and `server.listen(port, "localhost", () => {` use cases.

### Test links

Deploy preview: https://deploy-preview-9407--docusaurus-2.netlify.app/

## Related issues/PRs

#8202

### CODE REVIEW

File: packages/docusaurus/src/server/getHostPort.ts [hunk 1]
```diff
@@ -54,7 +54,10 @@ async function choosePort(
   defaultPort: number,
 ): Promise<number | null> {
   try {
-    const port = await detect({port: defaultPort, hostname: host});
+    const port = await detect({
+      port: defaultPort,
```
Comment (galaxypie) [inline packages/docusaurus/src/server/getHostPort.ts:58]: test

**Comment by slorber** [comment]
Thanks, that looks like a good-enough fix 👍
