### PR TITLE
Fix: Fix livereload on second try

### LINKED ISSUE #1091: Livereload not working on second try
## 🐛 Bug Report

The local server does not livereload anymore after the first livereload.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. Start the webserver
1. Edit anything v1/website/pages/index.js. See that the page refreshes.
1. Edit the same file again.

## Expected behavior

Page should refresh regardless of how many times.

## Actual Behavior

The page does not refresh. The reason is because the livereload script is not being sent down to the client after the first refresh. In `liveReloadServer.js`, the second call of `getReloadScriptUrl` returns  `undefined`. The module is probably unloaded and loaded again, causing the local `reloadScriptUrl` variable to lose its value. We probably shouldn't be storing local values within modules.

### PR DESCRIPTION
**Pull request by kahkhang**
## Motivation

Fixes LiveReload on second try (#1091), due to local variable defining livereload url losing its value during reload.

Fix #1091 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes!

## Test Plan

`yarn start`, then edited `v1/website/pages/index.js` multiple times. Ensured that live reload now works.

### CODE REVIEW

File: v1/lib/server/liveReloadServer.js [hunk 1]
```diff
@@ -9,10 +9,9 @@ const gaze = require('gaze');
 const tinylr = require('tiny-lr');
 const readMetadata = require('./readMetadata.js');
 
-let reloadScriptUrl;
-
 function start(port) {
   process.env.NODE_ENV = 'development';
+  process.env.PORT = port;
```
Comment (yangshun) [inline v1/lib/server/liveReloadServer.js]: This env variable is already being used by the webserver, so we can't call it `process.env.PORT`. Maybe `process.env.LIVERELOAD_PORT`?

Comment (kahkhang) [reply v1/lib/server/liveReloadServer.js]: Thanks for the catch!
