### PR TITLE
fix(v2): introduce useCollapsible to fix collapsible animation perf issues

### LINKED ISSUE #5099: Performance issues when expanding and collapsing the lists
### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [x] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [] I have tried creating a repro with https://new.docusaurus.io
- [] I have read the console error message carefully (if applicable)

### Description

When we collapse or expand the lists, it is processed with a slow speed.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## Steps to reproduce

1. Open the link:
https://docs.dhtmlx.com/suite/
2. Try collapsing and expanding the entries in the left menu.
3. It is done with a slow speed.

## Expected behavior

The entries should be expanded and collapsed with a higher speed.

## Actual behavior

The entries are expanded and collapsed with a slower speed.

## Your environment

- Public source code:
https://github.com/DHTMLX/docs-suite
- Public site URL:
https://docs.dhtmlx.com/suite/
- Docusaurus version used:
2.0
- Environment name and version (e.g. Chrome 78.0.3904.108, Node.js 10.17.0):
91.0.4472.106
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):
Xubuntu 18.04.5

## Reproducible demo

Demo:
https://docs.dhtmlx.com/suite/

Video:
https://files.dhtmlx.com/30d/755a3520f276b7a56857bc950354de17/vokoscreen-2021-06-30_16-56-23.mkv

### PR DESCRIPTION
**Pull request by lex111**
Edit by @slorber : original PR modified to use direct DOM element style application and avoid useless react re-renders on transitions

---

## Motivation

Should fix #5099

The current implementation of sidebar items accordion does not work well with large number of items, resulting in long delay when transition starts. More precise setting of styles for transition via `requestAnimationFrame` should make things right.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

As a test, you can use [this sidebar file](https://gist.github.com/lex111/93eb69daa3e6c4e627a639d2b18fc9ac), which contains enough links to reproduce the bug.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/hooks/useCollapse.ts [hunk 1]
```diff
@@ -0,0 +1,100 @@
...
+
+import {useState, useEffect, CSSProperties, useRef} from 'react';
+import type {
+  useCollapseProps,
+  useCollapseReturns,
+} from '@theme/hooks/useCollapse';
+
+function getAutoHeightDuration(height) {
+  const constant = height / 36;
+  return Math.round((4 + 15 * constant ** 0.25 + constant / 5) * 10);
```
Comment (lex111) [inline packages/docusaurus-theme-classic/src/theme/hooks/useCollapse.ts:16]: Dynamic transition duration is used in Material deisign, this technique is good for a large number of items. https://material.io/archive/guidelines/motion/duration-easing.html#duration-easing-dynamic-durations

File: packages/docusaurus-theme-classic/src/theme/hooks/useCollapse.ts [hunk 2]
```diff
@@ -0,0 +1,100 @@
...
+}
+
+const useCollapse = ({
```
Comment (lex111) [inline packages/docusaurus-theme-classic/src/theme/hooks/useCollapse.ts:19]: This hook also comes in handy in mobile TOC implementation.
