### PR TITLE
fix: wrong padding for single row mobile nav

### LINKED ISSUE #1187: 50px gap appears between title bar and nav bar when there are no header links
## 🐛 Bug Report

When you have no `headerLinks` and the width available to display your site goes below 1024px then the navbar (that takes the place of the left and right sidebars) appears below the title bar, however there is a 50px gap between the two (where a second bar containing the header links would go, if there were any).

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Set `headerLinks` to `[]` in `siteConfig.js`.
1. Open your site in your browser and resize your browser to reduce the width below 1024px.
1. At this width, the left and right sidebars disappear and are replaced by a navigation bar with left and right dropdowns.
1. The current CSS assumes the presence of hearer links that will appear in their own bar (when width is constrained). I.e. there should be a title bar, then a header bar and then a navbar.
1. However, if you have no `headerLinks` you just see empty space of 50px appear between the title bar and the navbar (note this really is a transparent empty space rather than an opaque space with no content - when you scroll your page you can see the underlying content scrolling upwards through this space).

## Expected behavior

When there are no `headerLinks` and the navbar appears it should appear directly below the title bar.

## Actual Behavior

Empty space appears between title bar and navbar.

## Reproducible Demo

```
git clone git@github.com:george-hawkins/arf-drone.git
git checkout 9ee75bb
```

### PR DESCRIPTION
**Pull request by marvinchin**
## Motivation

Fix #1187. Padding for certain components assumed that there will always be two rows in the nav bar in mobile view. Here we handle the case where the nav bar only has a single row on mobile devices.

I'm not 100% certain if `Site.js` is the best place to check whether the mobile nav bar occupies a single row, or if I'm applying the `singleRowMobileNav` class at the most suitable place. Please do let me know if there is a better way to achieve this!

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/Docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

We test for the cases where there are two rows in the mobile nav bar (at least 1 doc/blog/page/href/language link) and when there is one row in the mobile nav bar (no doc/blog/page/href/language link).

### Padding for mobile devices should be correct when there are two rows in the mobile nav bar:
screenshot 2019-01-20 at 12 58 50 am
screenshot 2019-01-20 at 12 58 59 am
screenshot 2019-01-20 at 12 59 10 am

### Padding for mobile devices should be correct when there is one row in the mobile nav bar:
screenshot 2019-01-20 at 1 05 15 am
screenshot 2019-01-20 at 1 05 21 am
screenshot 2019-01-20 at 1 05 30 am

### Padding for full screen devices should be correct when there are two rows in the mobile nav bar:
screenshot 2019-01-20 at 1 08 50 am

### Padding for full screen devices should be correct when there is one row in the mobile nav bar
screenshot 2019-01-20 at 1 07 57 am

### CODE REVIEW

File: v1/lib/core/Site.js [hunk 1]
```diff
@@ -7,19 +7,31 @@
...
 
 const CWD = process.cwd();
 
 // Component used to provide same head, header, footer, other scripts to all pages
 class Site extends React.Component {
+  mobileNavHasOneRow(headerLinks) {
+    const hasLanguageDropdown =
+      env.translation.enabled && env.translation.enabledLanguages().length > 1;
+    const ordinaryHeaderLinks = headerLinks.filter(
+      link => !link.languages && !link.search,
```
Comment (yangshun) [inline v1/lib/core/Site.js]: Can you change this to `link.languages || link.search`? It's easier to read.

File: v1/lib/core/Site.js [hunk 2]
```diff
@@ -7,19 +7,31 @@
...
+    );
+    const hasOrdinaryHeaderLinks = ordinaryHeaderLinks.length > 1;
+    return !hasLanguageDropdown && !hasOrdinaryHeaderLinks;
```
Comment (yangshun) [inline v1/lib/core/Site.js]: This too.

File: v1/lib/core/Site.js [hunk 3]
```diff
@@ -7,19 +7,31 @@
...
 const {idx} = require('./utils.js');
 
 const CWD = process.cwd();
 
 // Component used to provide same head, header, footer, other scripts to all pages
 class Site extends React.Component {
+  mobileNavHasOneRow(headerLinks) {
+    const hasLanguageDropdown =
+      env.translation.enabled && env.translation.enabledLanguages().length > 1;
+    const ordinaryHeaderLinks = headerLinks.filter(
```
Comment (yangshun) [inline v1/lib/core/Site.js]: Change to `headerLinks.some()` and you don't need to check for `.length > 1`.

**Comment by marvinchin** [comment]
@yangshun fixed!
