### PR TITLE
fix(v2): escape apostrophes in route paths

### LINKED ISSUE #3963: Does not build with an apostrophe in filenames
## 🐛 Bug Report

I started to use docusaurus for an existing documentation which has apostrophes in filenames sometimes.
When I build my project, I always have the following error:

```
SyntaxError: docusaurus2/.docusaurus/routes.js: Unexpected token, expected ","
{
  path: '/docs/Wiki/Project's-Guide',
  component: ComponentCreator('/docs2/Wiki/Project's-Guide','efe'),
  exact: true,
},
```

### Have you read the [Contributing Guidelines on issues]
I couldn't find anything related to this issue, after searching 'apostrophe'

## To Reproduce
Install Docusaurus
Create a filename such as docs/Project's-Guide.md

## Expected behavior
I would expect to find in router.js, something like:
component: ComponentCreator('/docs/Wiki/**Project\\'s-Guide**','efe'),

## Actual Behavior
For now, I have:
component: ComponentCreator('/docs2/Wiki/**Project's-Guide**','efe'),
And I'm not able to complete 'npm run build'

## Your Environment
I'm on MacOS using docusaurus version 2.0.0-alpha.70.

Is it something that could be fixed or do I have to write a workaround on my side to change the filenames and also the documents links ? 
Thank you for your help!

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Should fix #3963.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

See To reproduce section in #3963.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus/src/server/routes.ts [hunk 1]
```diff
@@ -136,7 +136,7 @@ export default async function loadRoutes(
     };
 
     return createRouteCodeString({
-      routePath: routeConfig.path,
+      routePath: routeConfig.path.replace(/'/g, "\\'"),
```
Comment (slorber) [inline packages/docusaurus/src/server/routes.ts:139]: was wondering, if using something like encodeURIComponent be a more general solution and handle other special chars?

Comment (lex111) [reply packages/docusaurus/src/server/routes.ts:139]: I don't think so, maybe it is worth resolving other cases when users will inform us about this?
