### PR TITLE
fix(theme): refactor Tabs, make groupId + queryString work fine together

### LINKED ISSUE #8473: Tab sync using groupId not functioning
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [X] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Tab sync does not seem to work, even when Tabs blocks have a similar groupId. This issue is present across latest Firefox and Chrome, and happens within the Docusaurus documentation itself.

### Reproducible demo

https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices

### Steps to reproduce

1. Go to the docusaurus docs website, markdown-features/tabs section
2. Try clicking the examples in the Syncing Tab Choices portion

### Expected behavior

The tabs for windows/mac should change in sync.

### Actual behavior

The tabs are unaffected by selections of one another.

### Your environment

- Public source code: https://github.com/facebook/docusaurus/blob/main/website/docs/guides/markdown-features/markdown-features-tabs.mdx?plain=1#L136
- Public site URL: https://docusaurus.io/docs/markdown-features/tabs#syncing-tab-choices
- Docusaurus version used: 
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Firefox 108, Chrome 108, Safari 16 17614 (All stock)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): Windows 11 Pro

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by slorber**
## Motivation

Fix #8473 (groupId/localStorage sync regression)

Much needed <Tabs> component refactor, make it easier to reason about and move most of the technical code to theme-common

## Test Plan

Unit tests + preview

### Test links

- https://deploy-preview-8486--docusaurus-2.netlify.app/docs/markdown-features/tabs

A good case to test: select "ios" on the 2nd/last tabs with a groupId (this will be persisted in localstorage)

- https://deploy-preview-8486--docusaurus-2.netlify.app/docs/markdown-features/tabs#query-string => show "android" + "ios"
- https://deploy-preview-8486--docusaurus-2.netlify.app/docs/markdown-features/tabs?current-os=android#query-string => shows "android" for both
- https://deploy-preview-8486--docusaurus-2.netlify.app/docs/markdown-features/tabs?current-os=ios#query-string => shows "ios" for both

(querystring wins over localstorage on purpose)

## Related issues/PRs

Supersed #8483

### CODE REVIEW

**Comment by slorber** [comment]
If anyone want to review this asap please let me know otherwise I'd like to merge it and do a release tomorrow

File: packages/docusaurus-theme-common/src/utils/storageUtils.ts [hunk 1]
```diff
@@ -5,12 +5,57 @@
...
+
+function subscribeChangeEvents(
+  onChange: (event: StorageSlotChangeEvent) => void,
+): () => void {
+  const listener = (domEvent: CustomEvent<StorageSlotChangeEvent>) =>
+    onChange(domEvent.detail);
+  // @ts-expect-error: TODO custom events are annoying to type
+  window.addEventListener(CustomEventName, listener);
+  // @ts-expect-error: TODO custom events are annoying to type
+  return () => window.removeEventListener(CustomEventName, listener);
```
Comment (0916dhkim) [inline packages/docusaurus-theme-common/src/utils/storageUtils.ts:56]: #### Suggestion
Maybe we can create a new event emitter instead of using `window`?
It might be easier to type.
https://basarat.gitbook.io/typescript/main-1/typed-event

File: packages/docusaurus-theme-common/src/utils/tabsUtils.tsx [hunk 2]
```diff
@@ -0,0 +1,262 @@
...
+    }
+    return value;
+  })();
+  useEffect(() => {
+    if (valueToSync) {
+      setSelectedValueState(valueToSync);
+    }
+  }, [valueToSync]);
+
+  const setSelectedValue = useCallback(
```
Comment (0916dhkim) [inline packages/docusaurus-theme-common/src/utils/tabsUtils.tsx:249]: Nit: What do you think about we name this function `selectValue` and name the `useState` setter `setSelectedValue`?

**Review by 0916dhkim — COMMENTED** [review]
Using `useSyncExternalStore` hook makes much more sense than using React context 👍

File: packages/docusaurus-theme-common/src/utils/storageUtils.ts (hunk 1 above)
Comment (slorber) [reply packages/docusaurus-theme-common/src/utils/storageUtils.ts:56]: 👍 

Actually I hesitated to bring my own tiny eventbus lib:
https://github.com/slorber/micro-typed-events

Another approach could be to emit regular storage events fired manually for the same window:
https://stackoverflow.com/a/71177640/82609
The interested is that you can use `addEventListener("storage")` and it would work for "same windows" localstorage changes, but also "cross window" localstorage changes, so it's an extra useful feature to have (groupId sync between different tabs)

**Comment by slorber** [comment]
LocalStorage sync now also works across windows 🥳  

https://user-images.githubusercontent.com/749374/209942108-eea85e04-1b94-409e-913d-6b6fb2addbcb.mp4
