### PR TITLE
fix(v2): disables all inlining in CleanCSS

### LINKED ISSUE #3942: @import, @font-face in CSS files causes builds to fail
## 🐛 Bug Report

Use of certain @ rules in CSS files causes builds to fail with no clear error message to help identify the issue. (Possible validation issue?) This makes it impossible to import other CSS files, most notably fonts, via custom.css or docusaurus.config.js. Removing any @ rules allows the build to complete successfully.

_(On a personal note, I feel it's worth mentioning that ever since Docusaurus attempted to validate literally everything it's been a horrible broken mess. Sites that previously worked now generate tons of errors that wouldn't be there if Docusaurus simply trusted developers that they actually intended to write the code they did. Most of the time we do.)_

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## To Reproduce

1. Initialize a new Docusaurus site
2. Upload a custom font to be served locally (mine are located in /static/fonts). [Example font](https://fonts.google.com/specimen/Abel?query=abel)
3. Add \@import to custom.css to import the font
4. `yarn run build` or `npm run build` (both produce the same result)

## Expected behavior

Build completes successfully and fonts are loaded in final build

## Actual Behavior

Build fails at 92% "OptimizeCssAssetsWebpackPlugin" with a very unhelpful error message:

**Node 14.x:**
```
undefined
(node:13766) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasErrors' of undefined
    at ../node_modules/@docusaurus/core/lib/webpack/utils.js:168:23
(node:13766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Node 15.x:**
```
undefined
../node_modules/@docusaurus/core/lib/webpack/utils.js:168
            if (stats.hasErrors()) {
                      ^

TypeError: Cannot read property 'hasErrors' of undefined
error Command failed with exit code 1.
```

## Your Environment

- Docusaurus version used: v2.0.0-alpha69, v2.0.0-alpha70
- Environment name and version: Node.js v14.15.3, v15.0.1
- Operating system and version: Debian 10

## Reproducible Demo

[Example repo](https://github.com/Lulech23/docusaurus-v2-bugreport/). Just install and build.

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Fixes  #3942

See https://github.com/jakubpawlowicz/clean-css/issues/914 and https://github.com/jakubpawlowicz/clean-css#inlining-options for more details.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

See To Reproduce section in #3942 issue.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus/src/webpack/utils.ts [hunk 1]
```diff
@@ -203,15 +203,15 @@ export function compile(config: Configuration[]): Promise<void> {
     const compiler = webpack(config);
     compiler.run((err, stats) => {
       if (err) {
-        reject(err);
+        reject(new Error(err.toString()));
```
Comment (slorber) [inline packages/docusaurus/src/webpack/utils.ts:206]: Was wondering, shouldn't we use an early return here?  
Or are there cases where we have both an error and stats?

**Comment by slorber** [comment]
Thanks, LGTM 👍

File: packages/docusaurus/src/webpack/utils.ts (hunk 1 above)
Comment (lex111) [reply packages/docusaurus/src/webpack/utils.ts:206]: I don't know, I think we'll leave it as it is for now, during the migration to webpack 5, let's get back to this.
