### PR TITLE
fix(v2): switch a toggle when system theme changed

### LINKED ISSUE #2295: [v2] Toggle theme component not reacting on change system theme
## 🐛 Bug Report

(A clear and concise description of what the bug is)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. start new project
2. go to system settings
3. change system theme
4. Toggle not change on current theme

## Expected behavior

Toggle will display the current theme

## Actual Behavior

Site theme changed but Toggle icons not reacting on changes.

(Write what happened. Add screenshots, if applicable.)
image

alpha.43

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolve #2295.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Go to preview and in the settings of your OS change the system theme to the opposite (dark -> light and vice versa). Make sure the theme and the toggle state in navbar change appropriately on the preview website.

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js [hunk 1]
```diff
@@ -61,6 +61,14 @@ const useTheme = () => {
     }
   }, [setTheme]);
 
+  useEffect(() => {
+    window
```
Comment (yangshun) [inline packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js]: Do we need to check for `disableDarkMode` here?

Comment (lex111) [reply packages/docusaurus-theme-classic/src/theme/hooks/useTheme.js]: Done!
