### PR TITLE
docs: fix website home testimonials broken image URLs

### LINKED ISSUE #8436: Image error control
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Motivation

Greetings, 

I am not 100% sure if this should be in the proposal part or the bug part but I chose to use the proposal issue because the thing I am going to write about is not exactly a bug, it is expected, I just think it can be handled in a better way. 

So when you go to https://docusaurus.io/ and go to the Loved by many engineers part, tweets come up(The code has a component and it is mapped over by the data). I believe some twitter images are breaking for example this screenshot: 

image

Mael and Kent's pictures' URL is broken and hence the img tag shows the alt name. I believe it would be much better if it showed a default avatar instead. This can be done in a few easy steps and I am willing (and excited) to work on this. 

What are my next steps? I am open to suggestions!

Thanks.

### Self-service

- [X] I'd be willing to do some initial work on this proposal myself.

### PR DESCRIPTION
**Pull request by abhinandanwadwa**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).
- [x] **If this is a code change**: I have written unit tests and/or added dogfooding pages to fully verify the new behavior.
- [x] **If this is a new API or substantial change**: the PR has an accompanying issue (closes #8436) and the maintainers have approved on my working plan.

## Motivation
As @slorber mentioned in issue #8436 , we can fix the broken link issue by adding a new prop `githubUsername` and GitHub has a defined image URL, which will always work but that will be passed as a fallback URL. The priority image will be fetched from the user's Twitter account using unavatar.io and the fallback would be the GitHub profile picture in case twitter image fails to load.

## Test Plan
I tried adding a broken twitter account username in the `handle` parameter and it still loads the image from GitHub's profile picture.

### Test links

Deploy preview: https://deploy-preview-8443--docusaurus-2.netlify.app/

Screenshot 2022-12-15 at 9 38 05 AM

## Related issues/PRs
#8436

### CODE REVIEW

**Comment by shawshankkumar** [comment]
Hey @abhinandanwadwa can you make this a draft at least for a week? Since I initiated the issue mentioned here and the maintainer said I can work on this, I would like to fix it or at least try. If I do not do it, maybe you can make this live again. But I'd like to try. CHeers.

File: website/src/data/tweets.tsx [hunk 1]
```diff
@@ -306,14 +288,13 @@ const TWEETS: TweetItem[] = [
       </>
     ),
     showOnHomepage: false,
+    githubUsername: '',
```
Comment (slorber) [inline website/src/data/tweets.tsx:291]:
```suggestion
    githubUsername: 'iansu',
```

**Review by slorber — COMMENTED** [review]
LGTM 👍
