### PR TITLE
fix(v2): allow external links in doc sidebar

### LINKED ISSUE #2185: External link in sidebar causes react warning
## 🐛 Bug Report

Adding a menu item of type `link` with an external `href` causes the following react warning:

> Warning: React does not recognize the `activeClassName` prop on a DOM element

Screenshot 2020-01-03 at 21 41 53

It looks that the culprit is in here https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/client/exports/Link.js#L72. Perhaps, we would ignore props related to `<Link>` before spreading to the anchor tag.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

## To Reproduce

1. In your custom sidebar.js file:

```js
module.exports = {
    docs: [
        {
            type: 'category',
            label: 'Some category',
            items: [
                {
                    type: 'link',
                    label: 'Docusaurus',
                    href: 'https://v2.docusaurus.io',
                },
            ],
        },
    ],
};

```

1. Run `npm start`
2. Open http://localhost:3000 and you should see the warning in the console.

## Expected behavior

No warning at all.

## Actual Behavior

The aforementioned warning appears in the console.

## Reproducible Demo

1. Clone `https://github.com/moxystudio/next-with-moxy`
2. `cd docusaurus && npm i && npm start`
3. Open http://localhost:3000 and see the warning on the console.

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Close #2185 

Currently, not possible to add an item with an external link in the doc sidebar.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Add an item with an external link in sidebars.js file, eg:

```js
          {
            type: 'link',
            label: 'Docusaurus',
            href: 'https://v2.docusaurus.io',
          },
```

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js [hunk 1]
```diff
@@ -10,6 +10,7 @@ import classnames from 'classnames';
 import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
 import useBaseUrl from '@docusaurus/useBaseUrl';
 import Link from '@docusaurus/Link';
+import isInternalUrl from '@docusaurus/utils'; // eslint-disable-line import/no-extraneous-dependencies
```
Comment (lex111) [inline packages/docusaurus-theme-classic/src/theme/DocSidebar/index.js]: This is not an external dep in this case, so this is a false positive ESLint..

**Comment by lex111** [comment]
@yangshun Hmm, it’s already done, isn’t it? https://v2.docusaurus.io/docs/sidebar/#link

**Comment by yangshun** [comment]
I mean documenting the new util function you just exposed

**Comment by lex111** [comment]
Is it really necessary for such a small function? In my opinion this is a self-describing function.

**Comment by yangshun** [comment]
I mean to write it in the website docs so that people even know about it and can use it if they want to, like in https://v2.docusaurus.io/docs/docusaurus-core#usebaseurl

**Comment by lex111** [comment]
Um, I don't think this is a good idea, because it is more of an internal function than a public API; this function is exported so that it can be reused.. would have done it differently, but in another way it is impossible (see https://github.com/facebook/docusaurus/blob/master/packages/docusaurus/src/webpack/base.ts#L65).

**Comment by lex111** [comment]
Explanation of the previous comment: we do not need to document everything that is in `client/exports` dir, for example, we have the helper function `ComponentCreator`, it is also publicly available, or `renderRoutes`.
Users can find out about this by looking at the source code, but if we do not document it on the website, then the use of these functions is the responsibility of the end-user. As a rule, users do not need a function to determine whether the route is internal or not, so I do not see much point in this.
