### PR TITLE
fix(theme-classic): fix mobile version dropdown label with only one version

### LINKED ISSUE #6309: Versions label not rendered in the mobile view mode
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [X] I have tried the `npm run clear` or `yarn clear` command.
- [X] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [X] I have read the console error message carefully (if applicable).

### Description

Versions labels are not rendered in the mobile view mode. 

### Steps to reproduce

Step 1: Define labels for versions in docusaurus.config.js
Step 2: Open website in the mobile view 
step 3: Click Menu icon in the top nav to see the "versions" text instead of labels. 

### Expected behavior

**Desired state:** I have a custom versions label defined in docusaurus.config.js.  The label title is displayed in the top navigation bar in the desktop browser mode. In the mobile mode, if you click the hamburger menu icon you see the label title.

### Actual behavior

**Current state:** I have a custom versions label defined in docusaurus.config.js.  The label title is displayed in the top navigation bar in the desktop browser mode. In the mobile mode, if you click the hamburger menu icon you see text "versions" instead of custom label title. 

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used:
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Reproducible demo

_No response_

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by Josh-Cena**
## Motivation

Fix #6309. #4986 is actually not very correct.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx [hunk 1]
```diff
@@ -64,7 +65,7 @@ export default function DocsVersionDropdownNavbarItem({
 
   // Mobile dropdown is handled a bit differently
   const dropdownLabel =
-    mobile && items
+    mobile && items.length > 1
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/NavbarItem/DocsVersionDropdownNavbarItem.tsx:68]: 🤪 good catch
