### PR TITLE
fix: make proper highlighting doc link if no sidebar

### LINKED ISSUE #5310: All navbar items without sidebar are active
### Prerequisites

- [x] I'm using the latest version of Docusaurus.

### Description

All navbar items without sidebar are active because of this condition: 
https://github.com/facebook/docusaurus/blob/081db7b35c4dcb64210f983bfc0640cc542c293e/packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx#L59

when there is no sidebar both `activeDoc.sidebar` and `doc.sidebar` are `undefined`.

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Steps to reproduce

https://codesandbox.io/s/practical-varahamihira-d2cw7?file=/sidebars.js

image

### PR DESCRIPTION
**Pull request by hamzahamidi**
## Motivation

Closes  #5310

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Write your test plan here. If you changed any code, please provide us with clear instructions on how you verified your changes work. Bonus points for screenshots and videos!)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx [hunk 1]
```diff
@@ -56,7 +56,7 @@ export default function DocNavbarItem({
       {...props}
       className={clsx(props.className, {
         [activeDocInfimaClassName]:
-          activeDoc && activeDoc.sidebar === doc.sidebar,
+          doc.sidebar && doc.sidebar === activeDoc?.sidebar,
```
Comment (lex111) [inline packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx:59]: Let's be closer to original condition and rewrite to something like this:

```suggestion
          activeDoc?.sidebar && activeDoc.sidebar === doc.sidebar,
```

**Review by lex111 — APPROVED** [review]

File: packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx [hunk 2]
```diff
@@ -56,7 +56,7 @@ export default function DocNavbarItem({
       {...props}
       className={clsx(props.className, {
         [activeDocInfimaClassName]:
-          activeDoc && activeDoc.sidebar === doc.sidebar,
+          activeDoc?.sidebar && activeDoc.sidebar === doc.sidebar,
```
Comment (fantua) [inline packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx:59]: in this case navbar items without sidebar always will be inactive?

Comment (slorber) [reply packages/docusaurus-theme-classic/src/theme/NavbarItem/DocNavbarItem.tsx:59]: No it would work fine because it's already the default behavior for a link to be active when we are on the link target page. We only need this additional class to enable the "tab-like" behavior.

**Comment by slorber** [comment]
👍
