### PR TITLE
fix(v2): avoid duplicated imports in npm2yarn plugin

### LINKED ISSUE #4544: @docusaurus/remark-plugin-npm2yarn redundant imports
## 🐛 Bug Report

The `@docusaurus/remark-plugin-npm2yarn` official plugin adds an import node for the `@theme/Tabs` and `@theme/TabItem` components if it successfully transforms a code block. This triggers a SyntaxError if the imports for them have already been defined in the file, or otherwise added (for example, through another plugin that fails to check for this).

    ./relative/path/to/file.mdx
    SyntaxError: absolute/path/to/file.mdx: Identifier 'Tabs' has already been declared (3:7)
    
      1 | import Tabs from '@theme/Tabs';
      2 | import TabItem from '@theme/TabItem';
    > 3 | import Tabs from '@theme/Tabs';
        |        ^

I don't know if it's the "proper" way to handle this, but I fixed it on my own end by matching nodes' values for each of the imports and using a boolean to keep track if they've been imported yet and only add the imports if a node was transformed and the imports were not found.

[Proposed rudimentary fix](https://gist.github.com/duanwilliam/f7ebe41e820b10086e4f9bbdb7c3698a)

### Have you read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## To Reproduce

1. Create a Docusaurus site
2. Make a markdown file that imports `Tabs` and/or `TabItem` ([such as this one from the docs](https://github.com/facebook/docusaurus/blob/master/website/docs/guides/markdown-features/markdown-features-tabs.mdx))
3. Install and configure `@docusaurus-remark-plugin-npm2yarn`
4. Add a valid npm2yarn code block.
    \`\`\`bash npm2yarn
    npm install
    \`\`\`
5. try to run the site.

## Expected behavior

The site runs normally.
The plugin should only add import nodes if no import node already exists.

## Actual Behavior

The site crashes.
The plugin adds import nodes even though they already exist.

## Your Environment

- Docusaurus version used: 2.0.0-alpha.72
- Environment name and version: Chrome 89.0.4389.90, Node.js 14.15.4
- Operating system and version (desktop or mobile):

### PR DESCRIPTION
**Pull request by lex111**
## Motivation

Resolves #4544

Currently, we cannot use `@docusaurus/remark-plugin-npm2yarn` plugin in document that already imports `Tabs`/`TabItem` components. This is because the plugin imports them no matter what they can already be imported in mdx doc file.

image

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Put the following code into any md file and try to start site.

````js
import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';

```bash npm2yarn
  $ npm install --global docusaurus
```

````

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/facebook/docusaurus, and link to your PR here.)

### CODE REVIEW

File: packages/docusaurus-remark-plugin-npm2yarn/src/index.js [hunk 1]
```diff
@@ -57,7 +57,11 @@ const nodeForImport = {
 module.exports = (options = {}) => {
   const {sync = false} = options;
   let transformed = false;
+  let alreadyImported = false;
   const transformer = (node) => {
+    if (node.type === 'import' && node.value.includes('@theme/Tabs')) {
```
Comment (lex111) [inline packages/docusaurus-remark-plugin-npm2yarn/src/index.js:62]: I intentionally check import only one `Tabs` component, because I think that using `TabItem` without importing `Tabs` makes no sense at all, so we can omit checking these two components.

File: packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/fixtures/import-tabs.md [hunk 2]
```diff
@@ -0,0 +1,7 @@
+import Tabs from '@theme/Tabs';
```
Comment (slorber) [inline packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/fixtures/import-tabs.md:1]: will it work if you use npm2yarn above the imports?

I think it will but I'd suggest adding usage of npm2yarn above/under the imports just to be 100% sure :)

**Review by slorber — APPROVED** [review]
Thanks, LGTM!

File: packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/fixtures/import-tabs.md (hunk 2 above)
Comment (lex111) [reply packages/docusaurus-remark-plugin-npm2yarn/src/__tests__/fixtures/import-tabs.md]: Yes, done it.

**Comment by slorber** [comment]
thanks 👍
