### PR TITLE
fix(theme-classic): add key prop for SimpleLinks map

### LINKED ISSUE #6509: SimpleLinks component missing unique "key" prop error
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#reporting-new-issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Using the following footer configuration:
```      
footer: {
  links: [
    {  label: "Link 1", href: "https://example.com/1" },
    {  label: "Link 2", href: "https://example.com/2" },
  ]
}
```

Results in this error:

Screen Shot 2022-01-29 at 10 49 17 AM

The `key` prop should be set on the fragment: https://github.com/kgajera/docusaurus/blob/main/packages/docusaurus-theme-classic/src/theme/Footer/index.tsx#L109

### Steps to reproduce

https://codesandbox.io/s/async-fire-9ps36

### Expected behavior

No error

### Actual behavior

Error in browser console:
```
react.development.js?1b7e:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `SimpleLinks`.
```

### Your environment

- Public source code:
- Public site URL:
- Docusaurus version used: 2.0.0-beta.15
- Environment name and version (e.g. Chrome 89, Node.js 16.4):
- Operating system and version (e.g. Ubuntu 20.04.2 LTS):

### Reproducible demo

https://codesandbox.io/s/async-fire-9ps36

### Self-service

- [X] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by kgajera**
## Motivation

Fixes #6509 

### Have you read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

Confirmed console error does not occur anymore

### CODE REVIEW

**Review by Josh-Cena — APPROVED** [review]
Thanks!

File: packages/docusaurus-theme-classic/src/theme/Footer/index.tsx [hunk 1]
```diff
@@ -106,10 +106,9 @@ function SimpleLinks({links}: {links: SimpleFooter['links']}) {
   return (
     <div className="footer__links">
       {links.map((item, key) => (
-        <>
+        <React.Fragment key={key}>
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/Footer/index.tsx:109]: Looks like we could prevent this with ESLint rule (disabled by default atm):

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md#checkfragmentshorthand-default-false

Comment (Josh-Cena) [reply packages/docusaurus-theme-classic/src/theme/Footer/index.tsx:109]: Interestingly, this rule is disabled in airbnb because of "false positives". I think we can enable some React rules ourselves

Comment (slorber) [reply packages/docusaurus-theme-classic/src/theme/Footer/index.tsx:109]: honnestly I never liked eslint airbnb, and many people have the same feeling

In the long term we should remove it imho

Comment (Josh-Cena) [reply packages/docusaurus-theme-classic/src/theme/Footer/index.tsx:109]: I like it as a solution that just works... We aren't tied to it (while many others are forced to have a style guide and stick to it) so we can tweak it however we want
