### PR TITLE
fix(theme): improve docs sidebar category caret aria-label accessibility

### LINKED ISSUE #9162: Screen reader announces incorrect label for the 'Expand/Collapse (Chevron)' button as 'Toggle the collapsible sidebar category 'Components'.
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of Docusaurus.
- [ ] I have tried the `npm run clear` or `yarn clear` command.
- [ ] I have tried `rm -rf node_modules yarn.lock package-lock.json` and re-installing packages.
- [ ] I have tried creating a repro with https://new.docusaurus.io.
- [ ] I have read the console error message carefully (if applicable).

### Description

Screen reader announces incorrect label for the 'Expand/Collapse (Chevron)' button as 'Toggle the collapsible sidebar category 'Components'.

User is not able to know role of the button.

Screen reader should announce about the group associated with suggestions available while navigating along the suggestions. 
i.e., When user enter the suggestions group, screen reader should announce as '<Group Name>and <suggestion name> along <position set>.

User with visual impairment who rely on screen reader will face difficulties if screen reader announces incorrect information if incorrect label for the 'Expand/Collapse (Chevron)' button.

### Reproducible demo

_No response_

### Steps to reproduce

**Pre-Requisites:** Scan off mode.

**Repro Steps:**
1.  Open https://www.fast.design/ URL.
2.  Navigate to link ‘Documentation’ and invoke it.
3.  Navigate to 'Expand/Collapse (Chevron)' button and activate it using 'Enter' key and listen to screen reader announcement.

### Expected behavior

Name property should be defined as 'Expand/Collapse Using the Components' and screen reader should announce as 'Expand using the Components' button when expanded and viceversa.

(or) 

Name property can be defined as 'Using the Components' and Aria Expand/collapse state should be defined.

On navigating screen reader should announce as 'Using the Components, button, Expanded' and viceversa. 

### Actual behavior

Screen reader announces incorrect label for the 'Expand/Collapse (Chevron)' button as 'Toggle the collapsible sidebar category 'Components'.

### Your environment

- Public source code: 
- Public site URL: https://www.fast.design/
- Docusaurus version used: Version: 2.4.1
- Environment name and version (e.g. Chrome 89, Node.js 16.4): Microsoft Edge
                                                                                                       **Version** 114.0.1823.86 (Official build) (64-bit)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS): **OS Name**:  Microsoft Windows 11 Enterprise
                                                                                              **Version**:   10.0.22621 Build 22621

### Self-service

- [ ] I'd be willing to fix this bug myself.

### PR DESCRIPTION
**Pull request by pinakipb2**
## Pre-flight checklist

- [x] I have read the [Contributing Guidelines on pull requests](https://github.com/facebook/docusaurus/blob/main/CONTRIBUTING.md#pull-requests).

## Motivation

Fixes #9162

### Test links

https://deploy-preview-9269--docusaurus-2.netlify.app/

## Related issues/PRs

#9162

### CODE REVIEW

File: packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx [hunk 1]
```diff
@@ -72,20 +72,35 @@ function useCategoryHrefWithSSRFallback(
...
     <button
       aria-label={translate(
         {
-          id: 'theme.DocSidebarItem.toggleCollapsedCategoryAriaLabel',
-          message: "Toggle the collapsible sidebar category '{label}'",
-          description:
-            'The ARIA label to toggle the collapsible sidebar category',
+          id: 'theme.DocSidebarItem.expandCategoryAriaLabel',
+          message: "Expand sidebar category '{label}'",
+          description: 'The ARIA label to expand the sidebar category',
```
Comment (slorber) [inline packages/docusaurus-theme-classic/src/theme/DocSidebarItem/Category/index.tsx:103]: we could have a ternary only on the aria-label prop instead of having 2 different button JSX here

**Review by slorber — CHANGES_REQUESTED** [review]
Reading https://github.com/facebook/docusaurus/pull/9269, I'm not 100% sure it's what @msftedad want, but we'll see when they review.

I'd prefer if you didn't duplicate the button JSX because only 1 prop is different for the 2 cases

**Comment by slorber** [comment]
@msftedad can you please review this PR and tell us if it improves accessibility for you? 

Preview url: https://deploy-preview-9269--docusaurus-2.netlify.app/

Thanks

**Comment by pinakipb2** [comment]
Hi @slorber its not "fix(a11y): fix docs sidebar category caret button accessibility, improve aria-label" as its not only for docs, it will affect the sidebar on every page using docusaurus. Its a change on the main product. The sidebar of the generated sites will have this a11y. Its better for users with screen readers to know if the sidebar category button is expand/collapse type so that they know the action they are performing.

**Comment by pinakipb2** [comment]
> > Hi @slorber its not **"fix(a11y): fix docs sidebar category caret button accessibility, improve aria-label"** as its not only for docs, it will affect the sidebar on every page using docusaurus. Its a change on the main product. The sidebar of the generated sites will have this a11y. Its better for users with screen readers to know if the sidebar category button is expand/collapse type so that they know the action they are performing.
> > _Ignore if you mean the documentation site(site generated by docusaurus) as docs._
> 
> Sorry but I don't understand 😅

Hi @slorber, people who are visually impaired rely on screen readers, the screen readers read the content of the website to them. But some complex components like button with a icon, its really hard for them(screen readers) to know the function of the button, and they don't know what to say aloud. So aria-label is used to so that they know what the button does and they say that aloud. So, in sidebar, in dropdown now the screen reader will say if the dropdown is collapsed on expanded, so the visually impaired person can know if clicking it will collapse the menu or expand it.
image

Hope you understand it now.

**Comment by pinakipb2** [comment]
@slorber @msftedad Have a look !

**Comment by pinakipb2** [comment]
@slorber @msftedad Have a look on the PR !

**Comment by pinakipb2** [comment]
Hi @slorber, as mentioned in https://github.com/facebook/docusaurus/issues/9162#issuecomment-1714937042 by @msftedad, you can now merge this PR.
Thanks !

**Review by slorber — APPROVED** [review]
Thanks 👍 

Just renamed the "isActive" props to "collapsed" because it's not super clear what isActive means if we extract later the button to a separate file
